/* Squad skill applicability, retired content and source cleanup. Never touches browser storage. */
(function(root){
 const clone=x=>JSON.parse(JSON.stringify(x));
 const resource=c=>['mana','stamina'].includes(c?.resource)||c?.spent||c?.moveCostMana||c?.moveCostStamina;
 const weapon=c=>c?.weapon||c?.anyWeapon;
 function effect(e){if(['refund','charge'].includes(e.type))return null;if(['restore','recover','drain'].includes(e.type)&&['mana','stamina'].includes(e.resource))return null;const v=clone(e);if(v.status){v.status.modifiers=(v.status.modifiers||[]).filter(m=>!m.stage.startsWith('cost:')&&!resource(m.conditions));if(!v.status.modifiers.length&&!v.status.tick&&!v.status.blocksAction&&!v.status.counterRatio)return null;}return v;}
 function source(skill){const s=clone(skill);s.modifiers=Object.fromEntries(Object.entries(s.modifiers||{}).filter(([k])=>!['mana','stamina'].includes(k)));s.statRates=Object.fromEntries(Object.entries(s.statRates||{}).filter(([k])=>!['mana','stamina'].includes(k)));s.growthRates=Object.fromEntries(Object.entries(s.growthRates||{}).filter(([k])=>!['mana','stamina'].includes(k)));s.combatModifiers=(s.combatModifiers||[]).filter(m=>!m.stage.startsWith('cost:')&&!['chargeRate','exp'].includes(m.stage)&&!resource(m.conditions)&&!weapon(m.conditions)&&!m.conditions?.chargeFull);s.hooks=(s.hooks||[]).filter(h=>!resource(h.conditions)&&!h.conditions?.isUltimate&&!h.conditions?.chargeFull&&!weapon(h.conditions)).map(h=>({...h,effects:(h.effects||[]).map(effect).filter(Boolean)})).filter(h=>h.effects.length);s.effects=(s.effects||[]).map(effect).filter(Boolean);s.elementCostReductionPct=0;s.damageToMpAbsorbPct=0;return s;}
 function allowed(skill){if(!skill||skill.id==='veteran'||skill.contentScope==='classExclusive'||skill.allowedClassIds?.length)return false;const s=source(skill);return !!(Object.keys(s.modifiers).length||Object.keys(s.statRates).length||Object.keys(s.growthRates).length||s.combatModifiers.length||s.hooks.length||s.elementDamageBonusPct||s.incomingElementDamageReductionPct);}
 function capabilityStats(base,growth,skills){return Object.fromEntries(Object.entries(base).map(([key,value])=>{const flat=skills.reduce((n,s)=>n+(s.modifiers?.[key]||0),0),baseRate=skills.filter(s=>s.baseOnly).reduce((n,s)=>n+(s.statRates?.[key]||0),0),totalRate=skills.filter(s=>!s.baseOnly).reduce((n,s)=>n+(s.statRates?.[key]||0),0),growthRate=skills.reduce((n,s)=>n+(s.growthRates?.[key]||0),0);return [key,(value*(1+baseRate)+flat+(growth[key]||0)*(1+growthRate))*(1+totalRate)];}));}
 function removedPart(skill){const s=JSON.stringify(skill);return /mana|stamina|elementCostReductionPct|damageToMpAbsorbPct/.test(s);}
 function description(skill,member=false){if(!member)return skill.description||'';if(!allowed(skill))return '此技能不適用隊員；資源、武器、職業與隊長必殺條件尚未開放。';return (skill.description||'').replace(/ 隊員沒有 MP／SP，此技能目前僅供隊長配置。/g,'').replace(/；僅隊長適用。/g,'。')+(removedPart(skill)?' 隊員僅套用傷害、減傷或其他有效效果；MP／SP 增加、消耗、恢復與資源條件效果一律忽略。':'');}
 function migrateProfile(p){if(p.skills?.veteran){p.retiredCollections=p.retiredCollections||{};p.retiredCollections.veteran=(p.retiredCollections.veteran||0)+p.skills.veteran;delete p.skills.veteran;}for(const m of p.members||[])m.skills=(m.skills||[]).filter(id=>id!=='veteran');}
 function clean(D){delete D.skills.veteran;for(const collection of [D.moves,D.skills,D.equipment])for(const item of Object.values(collection||{}))for(const key of ['sources','shopEligible','shopTier','shopCost','specName'])delete item[key];for(const key of ['world','monsters','explorationObjects','dungeons','books','enemySpawnData','dungeonTemplates','rewardPools','contentDistribution','resourceDistributionRules','catalogMoveIds','startingSkills','startingMoves'])delete D[key];if(D.contentV1)D.contentV1={version:D.contentV1.version};return D;}
 const api={capabilityStats,source,allowed,removedPart,description,migrateProfile,clean};if(typeof module!=='undefined')module.exports=api;else root.SquadSkills=api;
})(globalThis);
