/* Optional squad prototype. Original adventure balance and saves are independent. */
(function(root){
 const D=typeof module!=='undefined'?require('./data'):root.GameData;
 if(typeof module!=='undefined'){require('./content-v1');require('./classes');require('./content-copy')(D);require('./content-grades')(D);}
 const Members=typeof module!=='undefined'?require('./squad-members'):root.SquadMembers;
 const Loop=typeof module!=='undefined'?require('./squad-loop'):root.SquadLoop;
 const R=typeof module!=='undefined'?require('./skill-runtime'):root.SkillRuntime;
 const Core=typeof module!=='undefined'?require('./engine'):root.BattleCore;
 const Skills=typeof module!=='undefined'?require('./squad-skills'):root.SquadSkills;
 const clone=x=>JSON.parse(JSON.stringify(x));
 const config={version:8,loop:Loop.rules,enemyTarget:'front',step:.05,captain:{attack:84,magicAttack:70,hp:240,stamina:120,mana:100,agility:40,luck:10},captainAttack:8,captainInterval:2.8,travelSeconds:2.5,
  troops:{guard:{id:'guard',name:'盾衛',hp:110,attack:6,interval:2.8,reviveSeconds:10,damageRatio:.8,color:'#b8c8b1',description:'受到的傷害減少 20%；可配置於前排或後排。'},striker:{id:'striker',name:'劍士',hp:65,attack:10,interval:2.1,reviveSeconds:8,damageRatio:1,color:'#dfb780',description:'攻擊較快；倒下後 8 秒返回。'},mender:{id:'mender',name:'祈願者',hp:55,attack:3,interval:3.2,reviveSeconds:12,damageRatio:1,heal:7,description:'普攻時治療 HP 比例最低的存活隊員 7 HP。',color:'#93c9c2'}},
  moves:['quick','fire','interrupt','lesser_heal','double_slash','heavy','spark','frost'],
  waves:[{name:'霧徑史萊姆',sprite:'slime',hp:300,attack:18,cycle:2.8,moves:['slime']},{name:'荒原斥候',sprite:'goblin',hp:420,attack:26,cycle:2.7,moves:['slime','heavy']},{name:'灰牙獵獸',sprite:'wolf',hp:560,attack:35,cycle:2.4,moves:['slime','heavy']},{name:'岩甲守衛',sprite:'golem',hp:740,attack:45,cycle:2.8,moves:['heavy']},{name:'碎岩守關者',sprite:'golem',hp:1050,attack:62,cycle:2.8,moves:['slime','heavy'],boss:true,cleaveEvery:3,cleaveRatio:.45}]};
 Object.assign(config.troops,{
 ranger:{id:'ranger',name:'游俠',archetype:'striker',hp:58,attack:9,interval:1.8,reviveSeconds:9,damageRatio:1,color:'#91bfa0',description:'遠行弓手，出手迅速；可裝備物理招式。'},
 mage:{id:'mage',name:'元素使',archetype:'mender',hp:48,attack:13,interval:3.1,reviveSeconds:11,damageRatio:1,color:'#9c9fd8',description:'魔法攻擊手，高攻擊、低血量；可裝備魔法招式。'},
 priest:{id:'priest',name:'司祭',archetype:'mender',hp:62,attack:2,heal:10,interval:3.6,reviveSeconds:12,damageRatio:1,color:'#ddd2a5',description:'普攻時治療血量比例最低的存活隊員10HP；可裝備魔法招式。'},
 lancer:{id:'lancer',name:'槍兵',archetype:'striker',hp:82,attack:9,interval:2.6,reviveSeconds:9,damageRatio:1,color:'#b9b5d0',description:'血量與攻擊均衡；可裝備物理招式。'},
 knight:{id:'knight',name:'重甲騎士',archetype:'guard',hp:145,attack:5,interval:3.4,reviveSeconds:12,damageRatio:.75,color:'#abb7cb',description:'受到傷害減少25%，血量高、出手較慢；可裝備物理招式與前／後排護盾。'},
 rogue:{id:'rogue',name:'影刃',archetype:'striker',hp:50,attack:8,interval:1.5,reviveSeconds:7,damageRatio:1,color:'#aa8fac',description:'高頻率攻擊，血量較低；可裝備物理招式。'}
 });
 config.enemyCastMultiplier=1.4;config.enemyGroups={minimum:1,maximum:3};
 config.chests={chance:.25,gold:[15,35],afterlight:[3,7],skillChance:.15,moveChance:.15};
 for(const w of config.waves){w.hp=Math.round(w.hp*.6);w.cycle*=1.4;}
 config.moves=config.moves.filter(id=>D.moves[id]?.kind==='normal');
 const defaultBuild=()=>({talents:[],moves:['quick','fire','interrupt','lesser_heal'],ultimate:'fire',equipment:{head:null,chest:null,arms:null,feet:null,weapon:null}});

 const supportMoves={
  squad_heal:{id:'squad_heal',name:'艾妮司・雷姆',subtitle:'前線治癒',description:'治療 HP 比例最低的一名存活隊員，恢復該隊員最大 HP 的 30%。不會治療隊長，也不能復活倒下的隊員。',icon:'heart',kind:'normal',damageType:'magic',elements:['light'],multiplier:0,cost:{mana:11},attackTime:90,effects:[{type:'heal',ratio:.3}],ultimateChargeCost:110,squadSupport:'injuredTroop'},
  squad_ward:{id:'squad_ward',name:'露米亞・維爾',subtitle:'前排護盾',description:'僅為所有存活前排隊員各提供相當於自身最大 HP 20% 的護盾。護盾優先抵擋直接與持續傷害；同招重施只補至上限，不疊加。戰鬥結束或倒下後消失。',icon:'shield',kind:'normal',damageType:'magic',elements:['light'],multiplier:0,cost:{mana:14},attackTime:110,effects:[{type:'shield',ratio:.2}],ultimateChargeCost:110,squadSupport:'frontline'},
  squad_cleanse:{id:'squad_cleanse',name:'露米亞・菲亞',subtitle:'前排淨化',description:'僅移除所有存活前排隊員的負面狀態，包括持續傷害與凍結。不恢復 HP、不移除增益，也不能復活。',icon:'star',kind:'normal',damageType:'magic',elements:['light'],multiplier:0,cost:{mana:8},attackTime:85,effects:[{type:'cleanse'}],ultimateChargeCost:100,squadSupport:'afflictedFrontline'}
 };
 supportMoves.squad_rear_ward={...clone(supportMoves.squad_ward),id:'squad_rear_ward',name:'露米亞・諾維爾',subtitle:'後排護盾',description:supportMoves.squad_ward.description.replace('前排','後排'),squadSupport:'backline',powerGrade:'C'};
 supportMoves.squad_rear_cleanse={...clone(supportMoves.squad_cleanse),id:'squad_rear_cleanse',name:'露米亞・諾菲亞',subtitle:'後排淨化',description:supportMoves.squad_cleanse.description.replace('前排','後排'),squadSupport:'afflictedBackline',powerGrade:'C'};
 for(const [id,move]of Object.entries(supportMoves)){D.moves[id]=move;config.moves.push(id);}
 const polish=typeof module!=='undefined'?require('./squad-copy'):root.SquadCopy;polish(D);Skills.clean(D);
 // Import the existing player catalog; enemy-only attacks remain internal.
 const enemyMoves=new Set(['slime','goblin','wolf','crush','pulse']);
 config.moves=Object.keys(D.moves).filter(id=>!enemyMoves.has(id));
 config.loop.rewards.skillPool=Object.keys(D.skills);
 config.collectionRules={recruitCost:100,researchCost:15,rarityWeights:{C:60,B:28,A:9,S:2.7,SS:.3},duplicatePoints:{C:1,B:2,A:4,S:8,SS:16},exchangeCosts:{C:20,B:40,A:80,S:160,SS:320},moveDropChance:.01,starterMoves:['quick','fire','interrupt','lesser_heal','double_slash','heavy','spark','squad_heal','squad_ward','squad_cleanse']};
 function weighted(entries,rng){const total=entries.reduce((n,x)=>n+x[1],0);let n=rng()*total;for(const [id,w]of entries){n-=w;if(n<0)return id;}return entries.at(-1)[0];}

 const troopFields=(type)=>({stats:{hp:config.troops[type].hp,stamina:0,mana:0,agility:10,luck:0},stamina:0,mana:0,shield:0,statuses:{},cast:null,sequence:null,elements:[],weaponType:null});
 const serialActor=actor=>({...Object.fromEntries(Object.entries(actor).filter(([key])=>key!=='runtime')),runtimeOnce:actor.runtime?[...actor.runtime.once]:(actor.runtimeOnce||[])});
 function targetText(id){const move=D.moves[id],support=move?.squadSupport;if(support==='injuredTroop')return '目標：HP 比例最低的一名存活隊員';if(support)return '目標：所有存活'+(support.toLowerCase().includes('back')?'後排':'前排')+'隊員（不含隊長）';const hostile=move?.multiplier>0||move?.effects?.some(e=>e.type==='interrupt'||e.type==='freeze'||e.status?.target==='enemy'),self=move?.effects?.some(e=>['heal','shield','cleanse','restore','drain'].includes(e.type)||e.status?.target==='self');return [hostile?'傷害／控制目標：目前敵人':'',self?'恢復／增益對象：施放者自身':''].filter(Boolean).join('；')||'目標：目前敵人';}
 class SquadBattle extends Core.Battle{
  constructor(options,session){super(options);this.squad=session;this.enemyHits=0;this.enemies=[this.enemy];for(const t of session.crew){t.runtime=new R.Runtime(this,t,[{id:'troop-guard',name:'兵種防護',combatModifiers:[{stage:'incoming',op:'multiply',value:config.troops[t.type].damageRatio||1}]},...session.member(t).skills.map(id=>Skills.source(D.skills[id]))]);this[t.id]=t;}}
  isEnemy(actor){return actor===this.enemy||(this.enemies||[]).includes(actor);}
  setupGroup(count){const first=this.enemy;this.enemies=[first];if(count>1){first.id='foe-0';this[first.id]=first;for(let i=1;i<count;i++){const foe={...first,id:'foe-'+i,stats:{...first.stats},statuses:{},cast:null,sequence:null,shield:0,enemyTurn:0,rewarded:false};foe.runtime=new R.Runtime(this,foe,[]);this[foe.id]=foe;this.enemies.push(foe);}}first.enemyTurn=this.enemyTurn;first.rewarded=false;}
  settleDead(){for(const foe of this.enemies)if(foe.hp<=0&&!foe.rewarded){foe.rewarded=true;foe.cast=null;foe.sequence=null;const s=this.squad,w=s.encounter();s.stats.kills++;s.collect(w);s.trainParticipants(w);if(w.boss)s.stats.bossKills++;s.gainExp(w.exp*this.player.runtime.modify('exp',1));}}
  selectTarget(){const next=this.enemies.find(foe=>foe.hp>0);if(next)this.enemy=next;return next;}
  actionActors(){return [this.player,...this.enemies.filter(t=>t.hp>0),...this.squad.troops.filter(t=>t.hp>0)];}
  nextEnemyMove(actor=this.enemy){const list=this.enemyDefinition.moves;const turn=actor.enemyTurn??this.enemyTurn;actor.enemyTurn=turn+1;this.enemyTurn=actor.enemyTurn;return list[turn%list.length];}
  advance(seconds){if(this.phase!=='fighting')return;const until=this.time+seconds;while(this.phase==='fighting'){for(const foe of this.enemies)if(foe.hp>0&&!foe.cast&&!foe.sequence&&!this.isFrozen(foe))this.begin(foe,this.nextEnemyMove(foe));const actors=this.actionActors(),cast=actors.filter(a=>a.cast).sort((a,b)=>a.cast.endAt-b.cast.endAt)[0],sequence=actors.filter(a=>a.sequence).sort((a,b)=>a.sequence.nextAt-b.sequence.nextAt)[0],deadline=this.statusDeadline(),castAt=cast?.cast.endAt??Infinity,seqAt=sequence?.sequence.nextAt??Infinity,echoAt=this.delayedHits[0]?.at??Infinity,nextAt=Math.min(deadline,castAt,seqAt,echoAt);if(nextAt>until)break;this.elapse(nextAt);if(deadline===nextAt)this.processStatuses();else if(seqAt===nextAt)this.resolveSequenceHit(sequence);else if(echoAt===nextAt)this.resolveDelayedHit();else this.resolve(cast);}if(this.phase==='fighting')this.elapse(until);}
  processStatuses(){super.processStatuses();if(this.phase==='fighting'&&this.enemies.some(e=>e.hp<=0&&!e.rewarded))this.finish(true);}

  elapse(time){const dt=time-this.time;for(const t of this.squad.crew)if(!this.squad.troops.includes(t)){if(t.cast){t.cast.startedAt+=dt;t.cast.endAt+=dt;}if(t.sequence)t.sequence.nextAt+=dt;}super.elapse(time);}
  castDuration(move,actor){if(this.squad?.crew.includes(actor))return Math.max(.5,move.attackTime/Math.max(1,this.effectiveStat(actor,'agility')));if(this.isEnemy(actor)){const d=this.enemyDefinition;return Math.max(1.1,d.castCycle*move.attackTime/d.averageCast*Math.max(.25,actor.stats.agility)/Math.max(.25,this.effectiveStat(actor,'agility')))+.5;}return super.castDuration(move,actor);}
  damageValue(actor,target,move,critical=false,trace){if(actor===this.player){const ctx={actor,target,move,critical},power=this.effectiveStat(actor,move.damageType==='physical'?'attack':'magicAttack');let n=actor.runtime.modify('damage',power*move.multiplier,ctx,trace)*(1+actor.runtime.elementTotals(move.elements,trace).damageBonus);for(const m of move.reservedModifiers||[])if(move.consumeReserved&&R.matches(m.conditions,{...ctx,battle:this}))n=m.op==='add'?n+m.value:n*m.value;n*=R.elementMultiplier(move.elements,target.elements);if(this.isEnemy(target)){const rules=D.balance.enemyDefense||{},defense=move.damageType==='physical'?this.enemyDefinition.physicalDefense||0:this.enemyDefinition.magicResistance||0;n*=1-Math.min(rules.maximumReduction??.8,defense/((rules.formulaConstant||100)+defense));}if(critical)n*=this.rule('critMultiplier',actor,ctx);n=target.runtime.modify('incoming',n,{move,target:actor,critical},trace);return Math.max(0,n*(1-Math.min(D.balance.elementSkills?.maximumResistanceReduction??.95,target.runtime.elementTotals(move.elements,trace).incomingReduction)));}if(this.isEnemy(actor)){const ctx={actor,target,move,critical};let n=actor.runtime.modify('damage',actor.stats.attack/this.enemyDefinition.averageMultiplier*move.multiplier,ctx,trace)*(1+actor.runtime.elementTotals(move.elements,trace).damageBonus)*R.elementMultiplier(move.elements,target.elements);if(critical)n*=this.rule('critMultiplier',actor,ctx);return Math.max(0,target.runtime.modify('incoming',n,ctx)*(1-Math.min(.95,target.runtime.elementTotals(move.elements,trace).incomingReduction)));}if(!this.squad?.crew.includes(actor))return super.damageValue(actor,target,move,critical,trace);const ctx={actor,target,move,critical};let n=actor.runtime.modify('damage',actor.attack*move.multiplier,ctx,trace)*(1+actor.runtime.elementTotals(move.elements).damageBonus);for(const m of move.reservedModifiers||[])if(move.consumeReserved&&R.matches(m.conditions,{...ctx,battle:this}))n=m.op==='add'?n+m.value:n*m.value;n*=R.elementMultiplier(move.elements,target.elements);if(critical)n*=this.rule('critMultiplier',actor,ctx);return Math.max(0,target.runtime.modify('incoming',n,ctx)*(1-Math.min(.95,target.runtime.elementTotals(move.elements).incomingReduction)));}
  statusActors(){return [this.player,...(this.enemies||[this.enemy]).filter(t=>t.hp>0),...(this.squad?.crew||[]).filter(t=>t.hp>0)];}
  getMove(id,actor=this.player){const move=super.getMove(id,actor);if(move&&this.squad?.crew.includes(actor))move.cost={};if(move&&this.isEnemy(actor)&&this.squad){move.cost={};const wave=this.squad.encounter();move.attackTime*=config.enemyCastMultiplier;move.squadTarget=wave.targetRules?.[id]||config.enemyTarget;if(wave.cleaveEvery&&(this.enemyHits+1)%wave.cleaveEvery===0&&move.squadTarget==='front'){move.squadTarget='allFront';move.squadCleaveRatio=wave.cleaveRatio;}}return move;}
  enemyTargets(move){const alive=this.squad.troops.filter(t=>t.hp>0),front=alive.filter(t=>t.row==='front'),back=alive.filter(t=>t.row==='back');if(move.squadTarget==='captain'||!alive.length)return [this.player];if(move.squadTarget==='all')return [...alive,this.player];if(move.squadTarget==='allFront')return front.length?front:back.length?back:[this.player];const pool=move.squadTarget==='back'?(back.length?back:front):(front.length?front:back);return [pool[Math.min(pool.length-1,Math.floor(this.rng()*pool.length))]];}
  supportTargets(move){let alive=this.squad.troops.filter(t=>t.hp>0);if(move.squadSupport==='injuredTroop')return alive.filter(t=>t.hp<t.maxHp).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp).slice(0,1);if(move.squadSupport)alive=alive.filter(t=>t.row===(move.squadSupport.toLowerCase().includes('back')?'back':'front'));if(move.squadSupport?.startsWith('afflicted'))return alive.filter(t=>Object.values(t.statuses).some(s=>s.polarity==='debuff'&&s.expiresAt>this.time));return alive;}
  receiveDamage(actor,target,amount,move,critical=false,secondary=false,sourceId=null){
   // Compatibility for direct incoming packets. Resolved attacks and status ticks already have their own target.
   if(this.isEnemy(actor)&&target===this.player&&!secondary&&!move.squadResolved&&move.squadTarget!=='captain'&&move.squadTarget!=='all'){
    target=this.enemyTargets(move)[0];if(target!==this.player)amount=target.runtime.modify('incoming',amount,{move,target:actor});
   }
   if(target.hp<=0)return 0;
   const shieldBefore=target.shield,damage=super.receiveDamage(actor,target,amount,move,critical,secondary,sourceId);
   if(shieldBefore>target.shield)this.log('shield-hit','護盾吸收傷害',{actorId:actor.id,targetId:target.id,absorbed:shieldBefore-target.shield,moveId:move.id});
   const owner=actor===this.player?(move.id.startsWith('troop-')?move.id:'player'):actor.id;if(this.isEnemy(target)&&this.squad.stats.members[owner])this.squad.stats.members[owner].damage+=damage;if(this.squad.stats.members[target.id])this.squad.stats.members[target.id].taken+=damage;
   if(this.squad.crew.includes(target)){target.flashUntil=this.time+.2;if(damage>0)this.log('troop-hit',config.troops[target.type].name+'承傷',{actorId:actor.id,targetId:target.id,damage,moveId:move.id});if(target.hp<=0)this.squad.downTroop(target,this.time);}
   return damage;
  }
  recover(actor,resource,amount,ctx={}){const recovered=super.recover(actor,resource,amount,ctx),owner=ctx.move?.id?.startsWith('troop-')?ctx.move.id:ctx.actor?.id||'player';if(resource==='hp'&&this.squad?.stats.members[owner])this.squad.stats.members[owner].healing+=recovered;return recovered;}
  resolve(actor){
   if(actor===this.player||this.squad.crew.includes(actor)){const cast=actor.cast,move=cast.move||this.getMove(cast.moveId,actor);if(!move.squadSupport){actor.cast=null;const hostile=move.multiplier>0||move.effects.some(e=>e.type==='interrupt'||e.status?.target==='enemy');actor.sequence={moveId:move.id,move,spent:cast.spent||{},targetIds:[this.enemy.id],hits:hostile?(move.hits||1):1,index:0,nextAt:this.time,totalDamage:0,hitDamages:[],connectedIds:hostile?[]:[this.enemy.id]};this.resolveSequenceHit(actor);return;}actor.cast=null;const targets=this.supportTargets(move),ctx={actor,target:this.enemy,move,spent:cast.spent||move.cost,totalDamage:0,hitDamages:[],successfulSupport:false,healing:false};
    for(const target of targets)for(const effect of move.effects){if(effect.type==='heal'){const amount=actor.runtime.modify('healing',target.stats.hp*effect.ratio,ctx),healing=this.recover(target,'hp',amount,ctx);ctx.healing=true;ctx.successfulSupport=true;this.log('heal','前線治癒',{actorId:actor.id,targetId:target.id,moveId:move.id,healing});}
     else if(effect.type==='shield'){const before=target.shield;target.shield=Math.max(before,target.stats.hp*effect.ratio);ctx.successfulSupport=true;this.log('shield',move.subtitle,{actorId:actor.id,targetId:target.id,moveId:move.id,shield:target.shield-before});}
     else if(effect.type==='cleanse'){const removed=Object.values(target.statuses).filter(s=>s.polarity==='debuff').length;R.effects.cleanse(this,{...ctx,actor:target},effect);ctx.successfulSupport=true;this.log('cleanse',move.subtitle,{actorId:actor.id,targetId:target.id,moveId:move.id,removed});}}
    if(!targets.length)this.log('support-empty','施放完成時沒有可作用的存活隊員',{actorId:actor.id,moveId:move.id});actor.runtime.emit('OnSkillCastFinished',ctx);actor.runtime.emit('OnMagicSkillFinished',ctx);return;
   }
   const cast=actor.cast,move={...(cast.move||this.getMove(cast.moveId,actor)),squadResolved:true},targets=this.enemyTargets(move);actor.cast=null;this.enemyHits++;
   actor.sequence={moveId:move.id,move,spent:cast.spent||move.cost,targetIds:targets.map(t=>t.id),hits:move.hits||1,index:0,nextAt:this.time,totalDamage:0,hitDamages:[],connectedIds:[]};
   this.log(move.squadCleaveRatio?'cleave':'enemy-attack',move.squadCleaveRatio?'橫掃前排':'敵人出手',{actorId:actor.id,targetIds:targets.map(t=>t.id),moveId:move.id});this.resolveSequenceHit(actor);
  }
  resolveSequenceHit(actor){
   const sequence=actor.sequence;if(!sequence)return;const move=sequence.move;
   for(const [index,id]of sequence.targetIds.entries()){const target=this[id];if(!target||target.hp<=0)continue;
    if(actor.runtime.modify('accuracy',1,{move})<1&&this.rng()>actor.runtime.modify('accuracy',1,{move})){this.log('miss','MISS',{actorId:actor.id,targetId:id,moveId:move.id});continue;}
    if(this.rng()<this.rule('dodgeChance',target,{move})){if(target===this.player&&target.cast&&this.equipmentEffects.onDodgeShorten)target.cast.endAt=Math.max(this.time+.05,target.cast.endAt-this.equipmentEffects.onDodgeShorten);target.runtime.emit('OnDodge',{move,target:actor});this.log('dodge','閃避',{actorId:actor.id,targetId:id,moveId:move.id});continue;}
    if(!sequence.connectedIds.includes(id))sequence.connectedIds.push(id);
    if(move.multiplier>0){const critical=this.rng()<this.rule('critChance',actor,{move}),ratio=move.squadCleaveRatio&&index>0?move.squadCleaveRatio:1,damage=this.receiveDamage(actor,target,this.damageValue(actor,target,move,critical)*ratio/sequence.hits,move,critical);sequence.totalDamage+=damage;sequence.hitDamages.push(damage);this.log('damage',move.name,{actorId:actor.id,targetId:id,moveId:move.id,damage,critical,hit:sequence.index+1,hits:sequence.hits});if(damage>0)actor.runtime.emit('OnDamageDealt',{actor,target,move,damage,critical,totalDamage:sequence.totalDamage,hitDamages:[...sequence.hitDamages]});if(critical&&damage>0)actor.runtime.emit('OnCriticalHit',{actor,target,move,damage,critical});if(actor===this.player&&sequence.hits>1&&sequence.index===sequence.hits-1&&damage>0&&target.hp>0)for(const item of actor.runtime.sources)if(item.finisherEcho)this.queueEcho({actor,target,move,hitDamages:[damage],sourceId:item.id},item.finisherEcho);if(target===this.player&&target.hp<=0){actor.sequence=null;this.finish(false);return;}}
   }
   if(actor.hp<=0){actor.sequence=null;if(actor===this.player)this.finish(false);else if(this.isEnemy(actor))this.finish(true);return;}sequence.index++;if(sequence.index<sequence.hits&&(actor!==this.player||sequence.targetIds.some(id=>this[id]?.hp>0))){sequence.nextAt=this.time+(move.hitInterval??.18);return;}actor.sequence=null;
   const base={actor,move,spent:sequence.spent,totalDamage:sequence.totalDamage,hitDamages:sequence.hitDamages,successfulSupport:false,healing:false};
   for(const effect of move.effects||[]){const selfEffect=['heal','shield','restore','cleanse','drain','refund','charge'].includes(effect.type)||effect.status?.target==='self';for(const id of selfEffect?[sequence.targetIds[0]]:sequence.connectedIds){const target=this[id];if(!target||(!selfEffect&&target.hp<=0))continue;R.effects[effect.type](this,{...base,target},effect);}}
   const ctx={...base,target:this[sequence.targetIds[0]]};actor.runtime.emit('OnSkillCastFinished',ctx);actor.runtime.emit(move.damageType==='physical'?'OnPhysicalSkillFinished':'OnMagicSkillFinished',ctx);if(this.player.hp<=0)this.finish(false);else if(this.enemies.some(e=>e.hp<=0&&!e.rewarded))this.finish(true);
  }
  resolveDelayedHit(){const pending=this.delayedHits.shift();if(!pending)return;const actor=this[pending.actorId],target=this[pending.targetId],move=D.moves[pending.moveId];if(!actor||!target||target.hp<=0||actor.hp<=0||(this.squad.crew.includes(actor)&&!this.squad.troops.includes(actor)))return;const damage=this.receiveDamage(actor,target,pending.amount,move,false,true,pending.sourceId);this.log('afterimage','殘影',{actorId:actor.id,targetId:target.id,moveId:move.id,damage,secondary:true});if(this.isEnemy(target)&&target.hp<=0)this.finish(true);}

  finish(won){if(this.phase!=='fighting')return;if(won){this.settleDead();if(this.selectTarget())return;}this.lastOutcome={won,enemyHP:this.enemy.hp,enemyMaxHP:this.enemy.stats.hp};this.player.runtime.emit('OnBattleEnd',{won});this.enemy.runtime.emit('OnBattleEnd',{won:!won});for(const a of [this.player,...this.enemies,...this.squad.crew]){a.cast=null;a.sequence=null;a.statuses={};a.shield=0;}this.delayedHits=[];this.phase=won?'victory':'gameover';this.log(won?'victory':'death',won?'道路已清空':'隊長倒下');}
 }
 class Session{
  constructor(options={}){
   this.rng=options.rng||Math.random;this.groupSize=options.groupSize??null;if(this.groupSize!==null&&(!Number.isInteger(this.groupSize)||this.groupSize<1||this.groupSize>3))throw Error('敵人編組數量無效');this.profile=clone(options.profile||{gold:0,afterlight:0,skills:{}});this.runLoot={gold:0,afterlight:0,skills:{},moves:{}};Skills.migrateProfile(this.profile);this.build=clone(options.build||defaultBuild());this.build.talents=this.build.talents.filter(id=>id!=='veteran');this.validateBuild(this.build);
   const types=options.troops||['guard','striker','mender'];
   if(!this.profile.members)this.profile.members=types.map((type,i)=>Members.create('member-'+(i+1),type));if(!options.resume)for(const m of this.profile.members)Members.reset(m);this.profile.fragments=this.profile.fragments||{};for(const grade of Object.keys(Members.rules.rarities)){this.profile.fragments[grade]??=0;if(!Number.isSafeInteger(this.profile.fragments[grade])||this.profile.fragments[grade]<0)throw Error('碎片存檔無效');}
   this.profile.moves=this.profile.moves||Object.fromEntries(config.collectionRules.starterMoves.map(id=>[id,1]));this.profile.researchPoints??=0;if(!Number.isSafeInteger(this.profile.researchPoints)||this.profile.researchPoints<0)throw Error('研習點數存檔無效');if(this.build.talents.some(id=>!D.skills[id]||!(this.profile.skills[id]>0)))throw Error('技能尚未收藏');if(this.build.moves.concat(this.build.ultimate).some(id=>!(this.profile.moves[id]>0)))throw Error('招式尚未收藏');this.validateRoster();
   let selected=options.members;
   if(!selected&&options.troops){const used=new Set();selected=types.map(type=>{const m=this.profile.members.find(m=>m.type===type&&!used.has(m.id));if(!m)throw Error('此兵種沒有可用隊員');used.add(m.id);return m.id;});}
   selected=selected||this.profile.members.slice(0,3).map(m=>m.id);
   if(selected.length>3||new Set(selected).size!==selected.length||selected.some(id=>!this.profile.members.some(m=>m.id===id)))throw Error('最多配置三名不同隊員');
   this.crew=this.profile.members.map(m=>{const d=this.memberStats(m);return {...troopFields(m.type),id:'troop-'+(Number(m.id.slice(7))-1),memberId:m.id,type:m.type,hp:d.hp,maxHp:d.hp,stats:{...troopFields(m.type).stats,hp:d.hp,attack:d.attack,agility:d.speed,luck:d.luck},attack:d.attack,heal:d.heal,interval:d.interval,reviveAt:null,nextAttack:d.interval,flashUntil:0,moveCursor:0};});
   this.troops=selected.map((id,i)=>{const t=this.crew.find(t=>t.memberId===id);t.row='front';t.slot=i;return t;});this.participants=[];this.trainingThisRun={};
   this.wave=0;this.time=0;this.phase='travel';this.travelLeft=config.travelSeconds;this.paused=false;this.growth={level:0,exp:0};this.captain=this.maxStats();this.started=options.started!==false;this.charge=0;this.captainNext=0;this.stats={kills:0,downs:0,casts:0,ultimates:0,autoUltimates:0,bossKills:0,members:Object.fromEntries(['player',...this.crew.map(t=>t.id)].map(id=>[id,{damage:0,healing:0,taken:0,downs:0,casts:0}]))};this.growth={level:0,exp:0};this.autoFirst=!!options.autoFirst;this.travelChestChecked=false;this.lastChest=null;this.autoUltimate=!!options.autoUltimate;this.previousResult=clone(options.previousResult||null);this.battle=null;
  }
  validateBuild(build){Core.validateBuild(build);if(build.moves.length!==4||build.moves.some(id=>!config.moves.includes(id))||!config.moves.includes(build.ultimate))throw Error('試玩模式請配置四招與一個必殺');}
  validateRoster(){const roster=this.profile.members;if(!Array.isArray(roster)||new Set(roster.map(m=>m.id)).size!==roster.length)throw Error('隊員名冊無效');for(const m of roster){m.moves=m.moves||[];m.skills=m.skills||[];Members.validate(m);this.validateMemberLoadout(m,m.moves,m.skills);if(!config.troops[m.type])throw Error('未知隊員兵種');}}
  member(t){return this.profile.members.find(m=>m.id===t.memberId);}
  memberStats(member){return Members.stats(member,config.troops[member.type],(member.skills||[]).map(id=>Skills.source(D.skills[id])));}
  applyTraining(t){const d=this.memberStats(this.member(t)),ratio=t.hp/t.maxHp,changed=t.maxHp!==d.hp;t.maxHp=d.hp;t.stats.hp=d.hp;t.stats.attack=d.attack;if(t.hp>0&&changed)t.hp=Math.min(d.hp,ratio*d.hp);t.attack=d.attack;t.heal=d.heal;t.interval=d.interval;t.stats.agility=d.speed;t.stats.luck=d.luck;}
  trainParticipants(w){for(const id of this.participants){const m=this.profile.members.find(m=>m.id===id);if(!m)continue;const result=Members.train(m,w.boss?Members.rules.rewards.boss:Members.rules.rewards.normal);this.trainingThisRun[id]=(this.trainingThisRun[id]||0)+result.gained;const t=this.crew.find(t=>t.memberId===id);this.applyTraining(t);if(result.gained)this.battle.log('member-training','隊員培養',{actorId:t.id,memberId:id,...result});}}
  slots(member){const grade=Members.currentRarity(member);return {moves:{C:1,B:2,A:2,S:3,SS:4}[grade],skills:{C:1,B:1,A:2,S:3,SS:4}[grade]};}
  cultivateMember(id){if(this.started!==false&&this.phase!=='defeat')throw Error('永久培養只能在出發前或結算後進行');const m=this.profile.members.find(m=>m.id===id);if(!m)throw Error('尚未招募此隊員');const info=Members.cultivation(m);if(!info.next)throw Error('永久培養已達上限');if(this.profile.fragments[info.fragmentGrade]<info.cost)throw Error(info.fragmentGrade+' 級碎片不足');const result=Members.cultivate(m);this.profile.fragments[info.fragmentGrade]-=info.cost;this.applyTraining(this.crew.find(t=>t.memberId===id));return result;}
  compatible(member,id,kind='moves'){if(kind==='skills')return Skills.allowed(D.skills[id]);const move=D.moves[id];if(!config.moves.includes(id)||move.kind!=='normal')return false;const role=config.troops[member.type].archetype||member.type;if(role==='mender')return ['magic','heal','buff','defense'].includes(move.damageType);if(role==='striker')return move.damageType==='physical';return move.damageType==='physical'||['squad_ward','squad_rear_ward'].includes(id);}
  validateMemberLoadout(m,moves,skills){const slots=this.slots(m);for(const [kind,list]of Object.entries({moves,skills})){if(!Array.isArray(list)||list.length>slots[kind]||new Set(list).size!==list.length||list.some(id=>!this.compatible(m,id,kind)||!(this.profile[kind]?.[id]>0)))throw Error('隊員招式或技能不相容／尚未收藏');}}
  setMemberLoadout(memberId,moves,skills){const m=this.profile.members.find(m=>m.id===memberId);if(!m)throw Error('尚未招募此隊員');this.validateMemberLoadout(m,moves,skills);if(this.phase!=='defeat'&&this.started!==false&&JSON.stringify(skills)!==JSON.stringify(m.skills))throw Error('技能只能在出發前或結算後設定');m.moves=clone(moves);m.skills=clone(skills);if(this.started===false){const t=this.crew.find(t=>t.memberId===memberId);this.applyTraining(t);}}
  setSkills(ids){if(this.phase!=='defeat'&&this.started!==false)throw Error('技能只能在出發前或結算後設定');if(ids.length>4||new Set(ids).size!==ids.length||ids.some(id=>!(this.profile.skills[id]>0)||!D.skills[id]))throw Error('技能尚未收藏或重複配置');const before=this.maxStats();this.build.talents=clone(ids);if(this.started===false){const max=this.maxStats(),hp=this.captain.hp;this.captain={...max,hp:max.hp===before.hp?hp:hp/before.hp*max.hp,mana:Math.min(max.mana,this.captain.mana),stamina:Math.min(max.stamina,this.captain.stamina)};}}
  placeMember(memberId,row,slot){if(!['front','back'].includes(row)||!Number.isInteger(slot)||slot<0||slot>2)throw Error('站位無效');const incoming=this.crew.find(t=>t.memberId===memberId);if(!incoming)throw Error('尚未招募此隊員');const active=this.troops.includes(incoming),occupant=this.troops.find(t=>t.row===row&&t.slot===slot);if(!active&&!occupant&&this.troops.length>=3)throw Error('最多攜帶三名隊員');const old={row:incoming.row,slot:incoming.slot};if(occupant&&occupant!==incoming){if(active){occupant.row=old.row;occupant.slot=old.slot;}else this.troops[this.troops.indexOf(occupant)]=incoming;}if(!active&&!this.troops.includes(incoming))this.troops.push(incoming);incoming.row=row;incoming.slot=slot;if(this.phase==='fighting'&&!this.participants.includes(memberId))this.participants.push(memberId);if(this.battle)this.battle.log('formation','調整前後排',{memberId,row,slot});}
  removeMember(memberId){this.troops=this.troops.filter(t=>t.memberId!==memberId);}
  swapMember(index,memberId){const t=this.troops[index];if(!t)throw Error('隊員位置無效');this.placeMember(memberId,t.row,t.slot);}
  setLoadout(build){this.validateBuild(build);if(build.moves.concat(build.ultimate).some(id=>!(this.profile.moves[id]>0)))throw Error('招式尚未收藏');if(JSON.stringify(build.talents)!==JSON.stringify(this.build.talents))throw Error('技能只能在出發前設定');this.build=clone(build);if(this.battle)this.battle.build=clone(build);}
  tryChest(){const r=config.chests;if(this.rng()>=r.chance)return;const roll=range=>range[0]+Math.min(range[1]-range[0],Math.floor(this.rng()*(range[1]-range[0]+1))),gold=roll(r.gold),afterlight=roll(r.afterlight);for(const [key,n]of Object.entries({gold,afterlight})){this.profile[key]+=n;this.runLoot[key]+=n;}let item=null;const chance=this.rng();if(chance<r.skillChance){const pool=config.loop.rewards.skillPool,id=pool[Math.min(pool.length-1,Math.floor(this.rng()*pool.length))];item=this.awardCollection('skills',id);this.runLoot.skills[id]=(this.runLoot.skills[id]||0)+1;}else if(chance<r.skillChance+r.moveChance){const id=config.moves[Math.min(config.moves.length-1,Math.floor(this.rng()*config.moves.length))];item=this.awardCollection('moves',id);this.runLoot.moves[id]=(this.runLoot.moves[id]||0)+1;}this.lastChest={time:this.time,gold,afterlight,item};}
  awardCollection(kind,id){if(!['moves','skills'].includes(kind)||!D[kind][id])throw Error('收藏無效');const known=this.profile[kind][id]>0,grade=D[kind][id].powerGrade||'C',points=known?(config.collectionRules.duplicatePoints[grade]||1):0;this.profile[kind][id]=(this.profile[kind][id]||0)+1;this.profile.researchPoints+=points;return {kind,id,grade,duplicate:known,points};}
  research(kind){if(!['moves','skills'].includes(kind))throw Error('研習類型無效');const r=config.collectionRules,pool=kind==='moves'?config.moves:config.loop.rewards.skillPool,entries=Object.entries(r.rarityWeights).filter(([grade])=>pool.some(id=>(D[kind][id].powerGrade||'C')===grade));if(this.profile.afterlight<r.researchCost)throw Error('餘光點數不足');const grade=weighted(entries,this.rng),ids=pool.filter(id=>(D[kind][id].powerGrade||'C')===grade),id=ids[Math.min(ids.length-1,Math.floor(this.rng()*ids.length))];this.profile.afterlight-=r.researchCost;return this.awardCollection(kind,id);}
  exchange(kind,id){const pool=kind==='moves'?config.moves:kind==='skills'?config.loop.rewards.skillPool:[];if(!pool.includes(id))throw Error('兌換項目無效');if(this.profile[kind][id]>0)throw Error('已收藏此項目');const cost=config.collectionRules.exchangeCosts[D[kind][id].powerGrade||'C'];if(this.profile.researchPoints<cost)throw Error('研習點數不足');this.profile.researchPoints-=cost;return this.awardCollection(kind,id);}
  recruit(){const r=config.collectionRules;if(this.profile.gold<r.recruitCost)throw Error('金幣不足');const rarity=weighted(Object.entries(r.rarityWeights),this.rng),types=Object.keys(config.troops),type=types[Math.min(types.length-1,Math.floor(this.rng()*types.length))],duplicate=this.profile.members.find(m=>m.type===type&&m.rarity===rarity);if(duplicate){const fragments=Members.rules.cultivation.duplicateFragments;this.profile.gold-=r.recruitCost;this.profile.fragments[rarity]+=fragments;return {id:duplicate.id,type,rarity,duplicate:true,fragments,fragmentGrade:rarity};}const number=Math.max(0,...this.profile.members.map(m=>Number(m.id.slice(7))))+1,m=Members.create('member-'+number,type,rarity);m.moves=[];m.skills=[];const d=this.memberStats(m),t={...troopFields(type),id:'troop-'+(number-1),memberId:m.id,type,hp:d.hp,maxHp:d.hp,stats:{...troopFields(type).stats,hp:d.hp,attack:d.attack,agility:d.speed,luck:d.luck},attack:d.attack,heal:d.heal,interval:d.interval,reviveAt:null,nextAttack:this.time+d.interval,flashUntil:0,moveCursor:0};this.profile.gold-=r.recruitCost;this.profile.members.push(m);this.crew.push(t);this.stats.members[t.id]={damage:0,healing:0,taken:0,downs:0,casts:0};if(this.battle){t.runtime=new R.Runtime(this.battle,t,[{id:'troop-guard',combatModifiers:[{stage:'incoming',op:'multiply',value:config.troops[type].damageRatio||1}]}]);this.battle[t.id]=t;}return m;}
  collect(w){const r=config.loop.rewards,factor=1+(w.cycle-1)*.25,gold=Math.round((w.boss?r.bossGold:r.normalGold[w.templateIndex])*factor),afterlight=Math.round((w.boss?r.bossAfterlight:r.normalAfterlight[w.templateIndex])*factor);for(const [key,amount]of Object.entries({gold,afterlight})){this.profile[key]+=amount;this.runLoot[key]+=amount;}const pool=r.skillPool.filter(id=>D.skills[id]);let skill=null;if(pool.length&&this.rng()<(w.boss?r.bossSkillChance:r.normalSkillChance)){skill=pool[Math.min(pool.length-1,Math.floor(this.rng()*pool.length))];this.awardCollection('skills',skill);this.runLoot.skills[skill]=(this.runLoot.skills[skill]||0)+1;}let move=null;if(this.rng()<config.collectionRules.moveDropChance){move=config.moves[Math.min(config.moves.length-1,Math.floor(this.rng()*config.moves.length))];this.awardCollection('moves',move);this.runLoot.moves[move]=(this.runLoot.moves[move]||0)+1;}this.battle.log('loot','獲得收穫',{gold,afterlight,skill,move});}
  encounter(){return Loop.encounter(config.waves,this.wave);}
  maxStats(){const skills=this.build.talents.map(id=>D.skills[id]).filter(Boolean),growth=Object.fromEntries(Object.entries(config.loop.growth.perLevel).map(([key,value])=>[key,this.growth.level*value]));return Skills.capabilityStats(config.captain,growth,skills);}
  grade(){return Loop.grade(this.growth.level);}
  gainExp(amount){const before=this.maxStats(),start=this.growth.level,g=config.loop.growth;this.growth.exp+=amount;while(this.growth.level<g.maxLevel&&this.growth.exp>=g.xpBase+this.growth.level*g.xpPerLevel){this.growth.exp-=g.xpBase+this.growth.level*g.xpPerLevel;this.growth.level++;}if(this.growth.level>=g.maxLevel)this.growth.exp=0;if(this.growth.level===start)return;const after=this.maxStats();const hp=this.battle?.player.hp??this.captain.hp;this.captain.hp=after.hp===before.hp?hp:hp/before.hp*after.hp;if(this.battle){Object.assign(this.battle.player.stats,after);this.battle.player.hp=this.captain.hp;this.battle.log('growth','能力提升',{before,after,gained:this.growth.level-start,rankBefore:Loop.grade(start),rankAfter:this.grade()});}}
  reorderTroops(order){if(!Array.isArray(order)||order.length!==this.troops.length||new Set(order).size!==order.length||order.some(id=>!this.troops.some(t=>t.id===id)))throw Error('站位順序無效');const byId=new Map(this.troops.map(t=>[t.id,t]));this.troops=order.map(id=>byId.get(id));if(this.battle)this.battle.log('formation','調整隊員順序',{order:[...order]});}
  regenerate(seconds){const actor=this.phase==='fighting'?this.battle.player:this.captain,max=this.maxStats();for(const key of ['mana','stamina'])actor[key]=Math.min(max[key],actor[key]+seconds*config.loop.resourceRegen[key]);}
  tryAutoUltimate(){if(!this.autoUltimate||this.phase!=='fighting'||this.paused||this.battle.phase!=='fighting')return;const b=this.battle,m=b.getMove(this.build.ultimate);if(b.player.cast||b.player.sequence||b.isFrozen(b.player)||b.charge<(m.ultimateChargeCost||100)||Object.entries(m.cost).some(([key,n])=>b.player[key]<n))return;if(this.choose(4).ok)this.stats.autoUltimates++;}
  summary(){const w=this.encounter(),b=this.battle;return {loot:clone(this.runLoot),battleNumber:this.wave+1,cycle:w.cycle,kills:this.stats.kills,bossKills:this.stats.bossKills,time:Math.floor(this.time),stats:clone(this.stats),enemyName:w.name,enemyRemaining:b?Math.max(0,Math.ceil(100*b.enemy.hp/b.enemy.stats.hp)):100,boss:!!w.boss};}
  makeBattle(){
   this.participants=this.troops.map(t=>t.memberId);
   const w=this.encounter(),moves=w.moves.map(id=>D.moves[id]),averageMultiplier=moves.reduce((n,m)=>n+m.multiplier,0)/moves.length,averageCast=moves.reduce((n,m)=>n+m.attackTime,0)/moves.length;
   const b=new SquadBattle({build:this.build,stats:this.maxStats(),preserveResources:true,balance50:true,rules:{critChance:stats=>Math.min(D.balance.critCap,D.balance.critBase+stats.luck*D.balance.critPerLuck),dodgeChance:stats=>Math.min(D.balance.dodgeCap,stats.luck*D.balance.dodgePerAgility),critMultiplier:stats=>D.balance.critDamageBase+stats.luck*D.balance.critDamagePerLuck},enemy:{name:w.name,stats:{hp:w.hp,attack:w.attack,speed:100/w.cycle,stamina:0,mana:0,agility:10,luck:0},moves:w.moves,elements:[],attackPower:w.attack,averageMultiplier,averageCast,castCycle:w.cycle,balanceRole:w.boss?'boss':'normal',physicalDefense:8,magicResistance:8}},this);
   b.start();b.time=this.time;this.groupSize=w.boss?1:this.groupSize??(config.enemyGroups.minimum+Math.min(config.enemyGroups.maximum-config.enemyGroups.minimum,Math.floor(this.rng()*(config.enemyGroups.maximum-config.enemyGroups.minimum+1))));b.setupGroup(this.groupSize);if(!this.restoring)for(const t of this.troops)t.runtime.emit('OnBattleStart');b.enemy.cast=null;for(const foe of b.enemies){foe.cast=null;b.begin(foe,b.nextEnemyMove(foe));}for(const k of ['hp','stamina','mana'])b.player[k]=this.captain[k];b.charge=this.charge;this.captainNext=this.time+config.captainInterval;return b;
  }
  downTroop(t,time){if(t.reviveAt!==null)return;t.hp=0;t.shield=0;t.statuses={};t.cast=null;t.sequence=null;t.reviveAt=time+config.troops[t.type].reviveSeconds;this.stats.downs++;if(this.stats.members[t.id])this.stats.members[t.id].downs++;if(this.battle)this.battle.log('troop-down',config.troops[t.type].name+'暫時倒下',{actorId:t.id,targetId:t.id});}
  hurtTroop(t,amount,time){if(t.hp<=0)return;const damage=Math.min(t.hp,amount*(config.troops[t.type].damageRatio||1));t.hp=Math.max(0,t.hp-damage);t.flashUntil=time+.2;if(this.battle)this.battle.log('troop-hit',config.troops[t.type].name+'承傷',{targetId:t.id,damage});if(t.hp<=0)this.downTroop(t,time);}
  updateTroops(){for(const t of this.crew)if(t.hp<=0&&t.reviveAt!==null&&this.time>=t.reviveAt){t.hp=t.maxHp;t.reviveAt=null;t.nextAttack=this.time+t.interval;t.statuses={};t.shield=0;delete t.freezeImmuneUntil;if(this.battle)this.battle.log('troop-return',config.troops[t.type].name+'回到原站位',{actorId:t.id,targetId:t.id});}}
  basicHit(actor,move,base){const b=this.battle,target=b.enemy,ctx={actor,target,move};const accuracy=actor.runtime.modify('accuracy',1,ctx);if(accuracy<1&&b.rng()>accuracy){b.log('miss','MISS',{actorId:actor.id,targetId:target.id});return 0;}if(b.rng()<b.rule('dodgeChance',target,{move})){target.runtime.emit('OnDodge',{move,target:actor});b.log('dodge','閃避',{actorId:actor.id,targetId:target.id});return 0;}const critical=b.rng()<b.rule('critChance',actor,{move}),amount=actor.runtime.modify('damage',base,{move,target,critical})*(critical?b.rule('critMultiplier',actor,{move}):1),damage=b.receiveDamage(actor,target,amount,move,critical,true),hit={...ctx,critical,damage,totalDamage:damage,hitDamages:[damage]};if(damage>0&&actor.hp>0)actor.runtime.emit('OnDamageDealt',hit);if(critical&&damage>0&&actor.hp>0)actor.runtime.emit('OnCriticalHit',hit);return damage;}
  autoAttack(){const b=this.battle;if(b.phase!=='fighting')return;
   for(const t of this.troops){if(t.hp<=0||this.time<t.nextAttack||b.isFrozen(t)||t.cast||t.sequence)continue;const d=config.troops[t.type],equipped=this.member(t).moves;if(equipped.length){let id=null;for(let i=0;i<equipped.length;i++){const at=((t.moveCursor||0)+i)%equipped.length,candidate=equipped[at],move=b.getMove(candidate,t);if(move.squadSupport&&!b.supportTargets(move).length)continue;if(candidate==='lesser_heal'&&t.hp>=t.maxHp)continue;id=candidate;t.moveCursor=(at+1)%equipped.length;break;}if(id){const result=b.begin(t,id);if(result.ok){this.stats.members[t.id].casts++;t.nextAttack=this.time+b.castDuration(b.getMove(id,t),t)+t.interval;continue;}}}t.nextAttack=this.time+100/Math.max(1,b.effectiveStat(t,'agility'));
    const move={id:t.id,name:d.name,damageType:d.id==='mage'?'magic':'physical',elements:[],effects:[],cost:{}},damage=this.basicHit(t,move,t.attack);b.log('troop-attack',d.name+'出手',{actorId:t.id,targetId:b.enemy.id,damage});
    if(t.heal){const target=this.troops.filter(t=>t.hp>0&&t.hp<t.maxHp).sort((a,c)=>a.hp/a.maxHp-c.hp/c.maxHp)[0];if(target){const amount=t.runtime.modify('healing',t.heal,{move,actor:t,target}),heal=b.recover(target,'hp',amount,{move,actor:t,target});b.log('troop-heal',d.name+'治療',{actorId:t.id,targetId:target.id,heal});}}
    if(b.enemy.hp<=0){b.finish(true);return;}
   }
   if(this.time>=this.captainNext){this.captainNext=this.time+config.captainInterval*config.captain.agility/Math.max(1,b.effectiveStat(b.player,'agility'));if(!b.player.cast&&!b.player.sequence&&!b.isFrozen(b.player)){const move={id:'captain-basic',name:'隊長普攻',damageType:'physical',elements:[],effects:[],cost:{}},damage=this.basicHit(b.player,move,b.player.stats.attack*(config.captainAttack/config.captain.attack));b.log('captain-attack','隊長普攻',{actorId:'player',targetId:b.enemy.id,damage});if(b.enemy.hp<=0)b.finish(true);}}
  }
  choose(index){if(this.paused||this.phase!=='fighting')return {ok:false,reason:'等待交戰後施放'};const ultimate=index===4,id=ultimate?this.build.ultimate:this.build.moves[index],move=D.moves[id];if(!move)return {ok:false,reason:'未配置此招式'};if(move.squadSupport&&!this.battle.supportTargets(move).length)return {ok:false,reason:move.squadSupport==='injuredTroop'?'沒有受傷的存活隊員（不能復活）':move.squadSupport?.startsWith('afflicted')?'指定隊列沒有帶負面狀態的存活隊員':'指定隊列沒有存活隊員（不能復活）'};const result=this.battle.choose(id,ultimate);if(result.ok){this.stats.casts++;this.stats.members.player.casts++;if(ultimate)this.stats.ultimates++;}return result;}
  advance(seconds){if(!Number.isFinite(seconds)||seconds<0)throw Error('時間無效');if(this.paused||this.started===false||['defeat','complete'].includes(this.phase))return;
   let left=seconds;while(left>1e-9&&!['defeat','complete'].includes(this.phase)){const step=Math.min(config.step,left);left-=step;
    if(this.phase==='travel'){this.time+=step;this.travelLeft-=step;this.regenerate(step);this.updateTroops();if(!this.travelChestChecked&&this.travelLeft<=config.travelSeconds/2){this.travelChestChecked=true;this.tryChest();}if(this.travelLeft<=1e-9){this.battle=this.makeBattle();this.phase='fighting';}continue;}
    this.updateTroops();this.regenerate(step);this.tryAutoUltimate();if(this.autoFirst){const result=this.choose(0);if(result.ok)this.stats.autoFirstCasts=(this.stats.autoFirstCasts||0)+1;}this.battle.advance(step);this.time=this.battle.time;this.autoAttack();for(const k of ['hp','stamina','mana'])this.captain[k]=this.battle.player[k];this.charge=this.battle.charge;
    if(this.battle.phase==='gameover'){this.phase='defeat';break;}
    if(this.battle.phase==='victory'){this.battle.settleDead();this.wave++;this.groupSize=null;this.phase='travel';this.travelLeft=config.travelSeconds;this.travelChestChecked=false;}
   }
  }
  snapshot(){const b=this.battle,actor=serialActor;return {version:8,captainMax:this.battle?.player.stats||this.maxStats(),groupSize:this.groupSize,autoFirst:this.autoFirst,travelChestChecked:this.travelChestChecked,lastChest:clone(this.lastChest),started:this.started,profile:clone(this.profile),runLoot:clone(this.runLoot),growth:clone(this.growth),autoUltimate:this.autoUltimate,previousResult:clone(this.previousResult),build:clone(this.build),troops:clone(this.troops.map(serialActor)),crew:clone(this.crew.filter(t=>!this.troops.includes(t)).map(serialActor)),participants:[...this.participants],trainingThisRun:clone(this.trainingThisRun),wave:this.wave,time:this.time,phase:this.phase,travelLeft:this.travelLeft,captain:clone(b&&this.phase!=='travel'?{...this.captain,hp:b.player.hp,mana:b.player.mana,stamina:b.player.stamina}:this.captain),charge:this.charge,captainNext:this.captainNext,stats:clone(this.stats),battle:b?clone({enemies:b.enemies.map(serialActor),targetId:b.enemy.id,time:b.time,phase:b.phase,charge:b.charge,enemyTurn:b.enemyTurn,enemyHits:b.enemyHits,delayedHits:b.delayedHits,player:actor(b.player),enemy:actor(b.enemy),buildReport:b.buildReport}):null};}
  static restore(s){
   if(![1,2,3,4,5,6,7,8].includes(s?.version)||!Number.isSafeInteger(s.wave)||s.wave<0||(s.version<3&&s.wave>=config.waves.length)||!['travel','fighting','defeat','complete'].includes(s.phase)||!Number.isFinite(s.time)||s.time<0||!Array.isArray(s.troops)||s.troops.length>3)throw Error('試玩存檔無效');
   const profile=clone(s.profile||{gold:0,afterlight:0,skills:{}});
   if(s.version<4){profile.members=s.troops.map(t=>Members.create('member-'+(Number(t.id.slice(6))+1),t.type));}
   const activeIds=s.troops.map(t=>s.version<4?'member-'+(Number(t.id.slice(6))+1):t.memberId);
   const session=new Session({build:s.build,profile,resume:true,groupSize:s.version>=7?s.groupSize??null:1,members:activeIds,started:s.version>=5?s.started:true});
   for(const k of ['wave','time','phase','travelLeft','captain','charge','captainNext','stats'])session[k]=clone(s[k]);
   if(Object.values(session.captain).some(n=>!Number.isFinite(n)||n<0))throw Error('試玩存檔數值無效');
   if(s.version<3){session.wave=[0,2,5,8,10][s.wave];if(s.phase==='complete'){session.wave=11;session.phase='travel';session.travelLeft=config.travelSeconds;}const fresh=new Session().stats;session.stats={...fresh,...session.stats,members:fresh.members};session.stats.members.player.casts=session.stats.casts;if(s.phase==='complete')session.stats.bossKills=1;}
   else{session.growth=clone(s.growth);if(s.version<6){session.growth.level=Math.min(config.loop.growth.maxLevel,Math.max(0,session.growth.level-1));if(session.growth.level===config.loop.growth.maxLevel)session.growth.exp=0;}session.autoFirst=!!s.autoFirst;session.travelChestChecked=s.travelChestChecked===undefined?session.phase==='travel':!!s.travelChestChecked;session.lastChest=clone(s.lastChest||null);session.autoUltimate=!!s.autoUltimate;session.previousResult=clone(s.previousResult||null);session.runLoot={moves:{},...clone(s.runLoot||session.runLoot)};if(!Number.isInteger(session.growth.level)||session.growth.level<0||session.growth.level>config.loop.growth.maxLevel||!Number.isFinite(session.growth.exp)||session.growth.exp<0)throw Error('成長存檔無效');}
   Skills.migrateProfile(session.runLoot);
   for(const key of ['gold','afterlight'])if(!Number.isSafeInteger(session.profile[key])||session.profile[key]<0||!Number.isSafeInteger(session.runLoot[key])||session.runLoot[key]<0)throw Error('資源存檔無效');
   for(const collection of [session.profile.skills,session.runLoot.skills])if(!collection||Object.values(collection).some(n=>!Number.isSafeInteger(n)||n<0))throw Error('收藏存檔無效');
   const actors=s.version>=4?[...s.troops,...(s.crew||[])]:s.troops;
   if(!Array.isArray(actors)||actors.length!==profile.members.length||new Set(actors.map(t=>t.id)).size!==actors.length)throw Error('隊員狀態存檔無效');
   for(const saved of actors){const memberId=s.version<4?'member-'+(Number(saved.id.slice(6))+1):saved.memberId,t=session.crew.find(t=>t.memberId===memberId);if(!t||t.type!==saved.type||t.id!==saved.id||!Number.isFinite(saved.hp)||saved.hp<0||saved.hp>saved.maxHp||!Number.isFinite(saved.nextAttack)||!Number.isFinite(saved.maxHp)||saved.maxHp<=0||(saved.reviveAt!==null&&(!Number.isFinite(saved.reviveAt)||saved.reviveAt<0)))throw Error('隊員狀態存檔無效');Object.assign(t,clone(saved),{memberId});if(s.version<5){t.row='front';t.slot=activeIds.indexOf(memberId);t.moveCursor=0;}if(activeIds.includes(memberId)&&(!['front','back'].includes(t.row)||!Number.isInteger(t.slot)||t.slot<0||t.slot>2))throw Error('站位存檔無效');session.applyTraining(t);}
   session.troops=activeIds.map(id=>session.crew.find(t=>t.memberId===id));if(new Set(session.troops.map(t=>t.row+':'+t.slot)).size!==session.troops.length)throw Error('站位存檔重複');
   session.participants=s.version>=4?clone(s.participants):[...activeIds];session.trainingThisRun=s.version>=4?clone(s.trainingThisRun):{};
   if(!Array.isArray(session.participants)||new Set(session.participants).size!==session.participants.length||session.participants.some(id=>!profile.members.some(m=>m.id===id))||!session.trainingThisRun||Object.entries(session.trainingThisRun).some(([id,n])=>!profile.members.some(m=>m.id===id)||!Number.isSafeInteger(n)||n<0))throw Error('培養記錄存檔無效');
   if(s.battle&&session.phase!=='travel'){const participants=[...session.participants];session.restoring=true;session.battle=session.makeBattle();delete session.restoring;session.participants=participants;for(const k of ['time','phase','charge','enemyTurn','enemyHits','delayedHits','buildReport'])session.battle[k]=clone(s.battle[k]);for(const id of ['player','enemy']){if(id==='enemy'&&s.battle.enemies)continue;Object.assign(session.battle[id],clone(s.battle[id]));session.battle[id].runtime.once=new Set(s.battle[id].runtimeOnce||[]);if(id==='enemy'&&session.battle[id].stats.attack===undefined)session.battle[id].stats.attack=session.encounter().attack;}if(s.battle.enemies){if(s.battle.enemies.length!==session.battle.enemies.length)throw Error('敵人編組存檔無效');for(const saved of s.battle.enemies){const foe=session.battle.enemies.find(e=>e.id===saved.id);if(!foe||!Number.isFinite(saved.hp)||saved.hp<0||saved.hp>saved.stats.hp)throw Error('敵人編組存檔無效');Object.assign(foe,clone(saved));foe.runtime.once=new Set(saved.runtimeOnce||[]);}session.battle.enemy=session.battle.enemies.find(e=>e.id===s.battle.targetId)||session.battle.enemies[0];}for(const actor of session.battle.actionActors())if(actor.sequence&&!actor.sequence.targetIds){const id=actor.sequence.targetId==='enemy'?session.battle.enemy.id:actor.sequence.targetId;actor.sequence={...actor.sequence,targetIds:[id],connectedIds:actor.sequence.connected?[id]:[]};}for(const t of session.crew)t.runtime.once=new Set(t.runtimeOnce||[]);session.captainNext=s.captainNext;if(s.version===1&&session.battle.enemy.cast){const cast=session.battle.enemy.cast,move=session.battle.getMove(cast.moveId,session.battle.enemy);cast.move={...(cast.move||move),squadTarget:move.squadTarget,squadCleaveRatio:move.squadCleaveRatio};}if(s.version===1&&session.battle.enemy.sequence){const seq=session.battle.enemy.sequence,target=session.troops.find(t=>t.hp>0)||session.battle.player;seq.targetIds=[target.id];seq.connectedIds=seq.connected?[target.id]:[];seq.move={...seq.move,squadResolved:true};}}
   if(s.version<6){const max=session.maxStats(),actor=session.battle?.player;for(const key of ['hp','stamina','mana']){const amount=Math.min(max[key],actor?actor[key]:session.captain[key]);session.captain[key]=amount;if(actor)actor[key]=amount;}Object.assign(session.captain,Object.fromEntries(Object.entries(max).filter(([key])=>!['hp','stamina','mana'].includes(key))));if(actor)Object.assign(actor.stats,max);}
   const max=session.maxStats(),actor=session.battle?.player,oldHPMax=s.captainMax?.hp||s.battle?.player.stats.hp||(s.version>=8?max.hp:config.captain.hp+session.build.talents.reduce((n,id)=>n+(D.skills[id]?.modifiers?.hp||0),0)+session.growth.level*config.loop.growth.perLevel.hp*(1+session.build.talents.reduce((n,id)=>n+(D.skills[id]?.growthRates?.hp||0),0))),currentHP=actor?actor.hp:session.captain.hp;if(s.version>=6&&oldHPMax!==max.hp){session.captain.hp=currentHP/oldHPMax*max.hp;if(actor)actor.hp=session.captain.hp;}for(const key of ['mana','stamina']){session.captain[key]=Math.min(max[key],actor?actor[key]:session.captain[key]);if(actor)actor[key]=session.captain[key];}if(actor)Object.assign(actor.stats,max);session.paused=true;return session;
  }
 }
 const api={config,Session,Members,Skills,defaultBuild,targetText,KEY:'afterlight.squad.prototype.v1'};if(typeof module!=='undefined')module.exports=api;else root.SquadPrototype=api;
})(globalThis);
