(function(){
 const S=SquadPrototype,D=GameData,U=SquadPresentation,A=SquadAway,$=id=>document.getElementById(id),canvas=$('squad-canvas'),art=new SquadArt.Renderer(canvas);
 let pendingAway=null,backgroundAt=null,catchup=null,awayTimer=null;
 let session=null,draft={build:S.defaultBuild(),troops:['guard','striker','mender'],members:['member-1','member-2','member-3']},last=performance.now(),saveAt=0,activeBattle=null,cursor=0,messageUntil=0,tipTimer=null,growthAnimation=null;
 try{const raw=localStorage.getItem(S.KEY);if(raw){const saved=JSON.parse(raw);session=S.Session.restore(saved);pendingAway=A.metadata(saved);session.offlineReport=pendingAway?.report||null;draft={build:session.build,troops:session.troops.map(t=>t.type),members:session.troops.map(t=>t.memberId)};}}catch(_){session=null;}
 function save(){if(!session)return;try{const record=catchup?catchup.job.checkpoint():A.checkpoint(session,backgroundAt??Date.now(),pendingAway||{});localStorage.setItem(S.KEY,JSON.stringify(record));}catch(_){message('遠征進度無法儲存');}}
 function message(text){$('squad-message').textContent=text;messageUntil=performance.now()+2800;}
 function overlay(html,view='sheet'){
  $('squad-overlay').dataset.view=view;hideTip();$('squad-overlay').hidden=false;$('squad-panel-content').innerHTML=html;const first=$('squad-panel-content').querySelector('button');first?.focus();}
 function close(){hideTip();$('squad-overlay').hidden=true;last=performance.now();}

 function intro(initial=false){if(!initial)pendingAway=null;if(session){session.paused=true;if(!initial||!pendingAway)save();}pages.hide();overlay(`<div class="start-backdrop">${U.landscape()}</div><header class="start-brand"><h1 id="squad-panel-title"><span class="start-wordmark" lang="en">AFTERLIGHT</span><span class="start-title">餘光</span></h1><p class="start-subtitle">小隊遠征</p><span class="start-divider" aria-hidden="true"></span><p class="start-tagline">微光未熄，遠征不止。</p></header><button class="primary start-game" data-squad-action="enter">開始遊戲</button>`,'login');}
 function settings(){pages.open('settings');}
 try{const preference=JSON.parse(localStorage.getItem('afterlight.squad.preferences.v1')||'null');if(typeof preference?.reducedMotion==='boolean')art.reduced=preference.reducedMotion;}catch(_){}
 $('squad-game').dataset.reducedMotion=String(art.reduced);
 function savePreferences(){$('squad-game').dataset.reducedMotion=String(art.reduced);try{localStorage.setItem('afterlight.squad.preferences.v1',JSON.stringify({reducedMotion:art.reduced}));}catch(_){message('介面偏好無法儲存');}}


 function roster(){pages.open('collection');pages.collection='members';pages.render();}

 function configure(){pages.open('team');pages.team='config';pages.actor='player';pages.render();}
 function pause(){if(!session||catchup)return;pendingAway=null;if(session.phase==='defeat'){result();return;}session.paused=true;save();overlay(`<small>TAKE A BREATH</small><h1 id="squad-panel-title">遠征暫停</h1><p>隊員回場倒數與戰鬥都已暫停。</p><button class="primary" data-squad-action="resume">繼續遠征</button><button data-squad-action="configure">調整小隊配置</button><button data-squad-action="home">返回主畫面</button><button data-squad-action="settings">遊戲設定</button><button data-squad-action="collection">查看累積收穫</button><button data-squad-action="roster">隊員名冊與培養</button><small class="version-note">v${D.release.version}</small>`);}
 function result(){session.paused=true;growthAnimation=null;$('squad-growth').hidden=true;$('squad-formation-panel').hidden=true;save();pages.showResult();message('冒險已經結束');}
 function collection(){pages.open('collection');}
 function requestView(){try{document.documentElement?.requestFullscreen?.({navigationUI:'hide'})?.catch(()=>{});globalThis.screen?.orientation?.lock?.('portrait')?.catch(()=>{});}catch(_){}}
 function start(options){requestView();const previousResult=session?.phase==='defeat'?session.summary():session?.previousResult,autoUltimate=session?.autoUltimate||false,formation=options.formation||session?.troops.map(t=>({id:t.memberId,row:t.row,slot:t.slot}));session=new S.Session({...options,profile:session?.profile,previousResult,autoUltimate,autoFirst:session?.autoFirst||false});if(formation)for(const t of formation)if(session.troops.some(a=>a.memberId===t.id))session.placeMember(t.id,t.row,t.slot);draft={build:session.build,troops:session.troops.map(t=>t.type),members:session.troops.map(t=>t.memberId)};activeBattle=null;cursor=0;art.reset();growthAnimation=null;$('squad-growth').hidden=true;$('squad-formation-panel').hidden=true;close();labels();save();message('小隊出發 · 霧徑遠征開始');}
 $('squad-panel-content').addEventListener('click',e=>{const action=e.target.closest('[data-squad-action]')?.dataset.squadAction;if(!action||catchup)return;

  if(action==='enter'){requestView();enterGame();}else if(action==='away-continue'){close();labels();save();}else if(action==='away-retry')enterGame();else if(action==='home')intro();else if(action==='settings')settings();else if(action==='motion'){art.reduced=!art.reduced;savePreferences();settings();}else if(action==='fullscreen')requestView();else if(action==='roster')roster();else if(action==='collection')collection();else if(action==='configure')configure();else if(action==='resume'){if(session.started===false){configure();return;}if(session.phase==='defeat'){result();return;}requestView();session.paused=false;close();labels();save();}



 });
 $('formation-icon').innerHTML=U.icon('party');$('pause-icon').innerHTML=U.icon('pause');
 $('squad-pause').addEventListener('click',pause);
 $('squad-auto').addEventListener('click',()=>{if(!session||catchup)return;session.autoUltimate=!session.autoUltimate;save();paintHUD();});
 $('squad-formation').addEventListener('click',()=>{if(catchup)return;pages.open('team');pages.team='formation';pages.render();});
 function growthNotice(e){growthAnimation={...e,at:performance.now()};const names={attack:'攻擊力',magicAttack:'魔法攻擊力',hp:'HP',mana:'MP',stamina:'SP',agility:'速度',luck:'運氣'};$('squad-growth').innerHTML='<strong>LV UP！'+(e.rankBefore!==e.rankAfter?' · '+e.rankAfter:'')+'</strong><div>'+Object.keys(names).map(key=>`<span>${names[key]} <b id="growth-value-${key}">${e.before[key]}</b><small> +${Math.round((e.after[key]-e.before[key])*10)/10}</small></span>`).join('')+'</div>';$('squad-growth').hidden=false;}
 function paintGrowth(now){const e=growthAnimation;if(!e)return;const progress=art.reduced?1:Math.min(1,(now-e.at)/950);for(const key of Object.keys(e.before)){const value=e.before[key]+(e.after[key]-e.before[key])*(1-Math.pow(1-progress,3));$('growth-value-'+key).textContent=['attack','magicAttack','agility','luck'].includes(key)?value.toFixed(1):String(Math.round(value));}if(now-e.at>2400){$('squad-growth').hidden=true;growthAnimation=null;}}
 function labels(){const build=session?.build||draft.build;for(const button of document.querySelectorAll('[data-cast]')){const i=Number(button.dataset.cast),m=D.moves[i===4?build.ultimate:build.moves[i]];button.setAttribute('aria-label',(i===4?'必殺':'招式 '+ 'ABCD'[i])+'：'+m.name);if(i===4){button.querySelector('.ultimate-name').textContent=m.name;button.querySelector('.ultimate-name').classList.toggle('spell-name',!!m.subtitle);button.querySelector('.ultimate-subtitle').textContent=m.subtitle||'';button.querySelector('.ultimate-subtitle').hidden=!m.subtitle;button.querySelector('.ultimate-cost').textContent=U.cost(m);}else button.querySelector('.move-label').innerHTML=`<span class="move-emblem">${U.icon(m.icon||'sword')}<em>${'ABCD'[i]}</em></span>`+(m.subtitle?`<strong class="spell-name">${U.escape(m.name)}</strong><span class="skill-subtitle">${U.escape(m.subtitle)}</span>`:`<strong>${U.escape(m.name)}</strong>`)+`<small class="actual-cost">${U.escape(U.cost(m))}</small>`;}}
 function hideTip(){clearTimeout(tipTimer);$('squad-tip').hidden=true;}
 function showTip(button){const i=Number(button.dataset.cast),id=i===4?(session?.build||draft.build).ultimate:(session?.build||draft.build).moves[i],move=session?.battle?.preview(id)||D.moves[id];$('squad-tip').innerHTML=`<h3>${U.escape(move.name)}</h3>${move.subtitle?`<p>${U.escape(move.subtitle)}</p>`:''}<p>${U.escape(U.cost(move))}${move.castTime?' · 讀條 '+move.castTime.toFixed(1)+' 秒':''}</p><p>${U.escape(move.description||'')}</p><p>${U.escape(S.targetText(id))}</p><p>${U.escape(U.effects(move))}</p>`;$('squad-tip').hidden=false;}
 for(const button of document.querySelectorAll('[data-cast]')){let suppressed=false,origin=null;
  button.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'){hideTip();tipTimer=setTimeout(()=>showTip(button),600);}});
  button.addEventListener('pointerleave',hideTip);
  button.addEventListener('pointerdown',e=>{if(e.button!==0)return;origin={x:e.clientX,y:e.clientY};suppressed=false;hideTip();tipTimer=setTimeout(()=>{suppressed=true;showTip(button);},450);});
  button.addEventListener('pointermove',e=>{if(origin&&Math.hypot(e.clientX-origin.x,e.clientY-origin.y)>12){suppressed=true;hideTip();}});
  button.addEventListener('pointerup',()=>{clearTimeout(tipTimer);origin=null;});button.addEventListener('pointercancel',()=>{suppressed=true;origin=null;hideTip();});
  button.addEventListener('contextmenu',e=>{e.preventDefault();suppressed=true;showTip(button);});
  button.addEventListener('click',()=>{if(suppressed){suppressed=false;return;}hideTip();const response=session?.choose(Number(button.dataset.cast));if(response&&!response.ok)message(response.reason);save();});
 }
 // Match the original directional controls. Physical codes also work with Chinese input enabled.
 const combatKeys={KeyW:0,ArrowUp:0,Digit1:0,KeyD:1,ArrowRight:1,Digit2:1,KeyS:2,ArrowDown:2,Digit3:2,KeyA:3,ArrowLeft:3,Digit4:3,Space:4,Digit5:4};
 const combatKeyNames={w:0,arrowup:0,'1':0,d:1,arrowright:1,'2':1,s:2,arrowdown:2,'3':2,a:3,arrowleft:3,'4':3,' ':4,'5':4};
 document.addEventListener('keydown',e=>{
  if(!$('squad-overlay').hidden||pages.tab!=='adventure'||pages.adventureState||e.ctrlKey||e.metaKey||e.altKey||e.target?.isContentEditable||['INPUT','TEXTAREA','SELECT'].includes(e.target?.tagName))return;
  const key=(e.key||'').toLowerCase(),index=combatKeys[e.code]??combatKeyNames[key];
  if(index!==undefined){e.preventDefault();if(e.repeat)return;hideTip();const r=session?.choose(index);if(r&&!r.ok)message(r.reason);save();}
  else if((e.code==='Escape'||key==='escape')&&!e.repeat){e.preventDefault();pause();}
 });
 document.addEventListener('visibilitychange',()=>{if(document.hidden){backgroundAt??=Date.now();hideTip();save();}else returnFromAway();});window.addEventListener('pagehide',save);window.addEventListener('pageshow',e=>{if(e.persisted)returnFromAway(true);});
 function awayNotice(){if(!session.offlineReport)return;overlay(`<small>WHILE YOU WERE AWAY</small><h1 id="squad-panel-title">離線冒險收穫</h1>${pages.offlineSummary()}<p>小隊正在繼續冒險。</p><button class="primary" data-squad-action="away-continue">繼續冒險</button>`);}
 function openAdventure(show=false){if(!session||session.started===false){configure();return;}if(session.phase==='defeat'){result();return;}pages.hide();session.paused=false;close();labels();save();if(show)awayNotice();}
 function enterGame(){if(catchup)return;const meta=pendingAway;pendingAway=null;if(meta?.running&&A.eligible(session)&&Date.now()>meta.at){beginAway(meta,openAdventure);return;}openAdventure();}
 function returnFromAway(fromCache=false){if(document.hidden)return;if(catchup){scheduleAway();return;}if(backgroundAt===null&&!fromCache)return;backgroundAt=null;last=performance.now();if(pendingAway||!session)return;let meta;try{meta=A.metadata(JSON.parse(localStorage.getItem(S.KEY)||'null'));}catch(_){}if(meta?.running&&A.eligible(session)&&Date.now()>meta.at)beginAway(meta,show=>{if(session.phase==='defeat'){result();return;}session.paused=false;close();pages.render();labels();save();if(show)awayNotice();});}
 function scheduleAway(){clearTimeout(awayTimer);awayTimer=setTimeout(pumpAway,0);}
 function beginAway(meta,onDone){const job=new A.Catchup(session,meta,Date.now());if(job.done){onDone(false);return;}if(job.total<1){job.step(job.total);last=performance.now();activeBattle=session.battle;cursor=activeBattle?.events.length||0;shownChest=session.lastChest;onDone(false);return;}catchup={job,onDone};backgroundAt=null;growthAnimation=null;$('squad-growth').hidden=true;overlay(`<small>遠征仍在繼續</small><h1 id="squad-panel-title">正在結算離線冒險</h1><p id="away-progress" role="status">離線 ${A.duration(job.total)}，正在計算戰鬥與收穫…</p>`);scheduleAway();}
 function pumpAway(){if(!catchup||document.hidden)return;const current=catchup,job=current.job,budget=performance.now();try{for(let i=0;i<20&&!job.done;i++){job.step(5);if(performance.now()-budget>=10)break;}save();$('away-progress').textContent='已推進 '+A.duration(job.processed)+' · 擊敗 '+(session.stats.kills-job.base.kills)+' 隻敵人';if(!job.done){scheduleAway();return;}job.finish(Date.now());catchup=null;backgroundAt=null;pendingAway=null;last=performance.now();activeBattle=session.battle;cursor=activeBattle?.events.length||0;shownChest=session.lastChest;art.reset();save();current.onDone(true);}catch(error){console.error('Offline adventure failed',error);catchup=null;try{const saved=JSON.parse(localStorage.getItem(S.KEY));session=S.Session.restore(saved);pendingAway=A.metadata(saved);session.offlineReport=pendingAway?.report||null;}catch(_){}if(session)session.paused=true;overlay(`<h1 id="squad-panel-title">離線冒險尚未完成</h1><p>已保留上次成功儲存的進度，可以重新結算。</p><button class="primary" data-squad-action="away-retry">再試一次</button>`);}}

 function stableHTML(id,html){const element=$(id);if(element.innerHTML!==html)element.innerHTML=html;}
 let shownChest=null;function paintHUD(){const s=session;if(!s)return;if(s.lastChest&&shownChest!==s.lastChest){shownChest=s.lastChest;const c=s.lastChest;message('寶箱 · 金幣 +'+c.gold+' · 餘光 +'+c.afterlight+(c.item?' · '+D[c.item.kind][c.item.id].name+(c.item.points?' · 研習 +'+c.item.points:''):''));}$('squad-game').dataset.phase=s.phase;$('squad-auto').textContent=s.autoUltimate?'必殺 自動':'必殺 手動';$('squad-auto').setAttribute('aria-pressed',String(s.autoUltimate));const w=s.encounter(),b=s.battle,fighting=s.phase==='fighting';$('squad-enemy-info').hidden=!fighting;$('squad-wave').textContent=`第 ${w.cycle} 輪 · ${w.boss?'BOSS 戰':'普通戰 '+w.position+' / 10'} · 第 ${s.wave+1} 場`;$('squad-enemy-name').textContent=w.name+(fighting&&b.enemies?.length>1?' · '+b.enemies.filter(e=>e.hp>0).length+'/'+b.enemies.length:'');$('squad-enemy-health').textContent=Math.ceil(fighting?Math.max(0,b.enemy.hp):w.hp)+' / '+Math.ceil(fighting?b.enemy.stats.hp:w.hp);$('squad-enemy-hp').style.width=(fighting?100*b.enemy.hp/b.enemy.stats.hp:100)+'%';const cast=fighting?b.enemy.cast:null,targetLabel=cast?.move?.squadTarget==='allFront'?'全體前排':cast?.move?.squadTarget==='captain'?'隊長':cast?.move?.squadTarget==='back'?'後排優先':cast?.move?.squadTarget==='all'?'全體':s.troops.some(t=>t.hp>0&&t.row==='front')?'前排隨機':s.troops.some(t=>t.hp>0)?'後排隨機':'隊長';$('squad-enemy-cast').style.width=(cast?Math.min(100,100*(b.time-cast.startedAt)/cast.duration):0)+'%';$('squad-enemy-action').textContent=cast?D.moves[cast.moveId].name+' · '+targetLabel+' · '+Math.max(0,cast.endAt-b.time).toFixed(1)+'s':s.phase==='travel'?'前方發現敵人':s.phase==='defeat'?'隊長倒下':'準備出手';
  const actor=fighting?b.player:s.captain;const maxima=s.maxStats();const resourceHTML=[['hp','HP','hp'],['stamina','SP','sp'],['mana','MP','mp']].map(([key,name,cls])=>`<div class="vital-row ${cls}"><span>${name}</span><div><i style="width:${Math.round(1000*actor[key]/maxima[key])/10}%"></i></div><small>${Math.ceil(actor[key])} / ${Math.round(maxima[key])}</small></div>`).join('');stableHTML('squad-resources',resourceHTML);const playerCast=fighting?b.player.cast:null;$('squad-cast-name').textContent='隊長 '+s.grade()+' · '+(playerCast?D.moves[playerCast.moveId].name:'隊長準備就緒')+(fighting?[(actor.shield>0?'護盾 '+Math.ceil(actor.shield):''),...Object.values(actor.statuses).filter(v=>v.expiresAt>s.time).map(v=>v.name)].filter(Boolean).map(v=>' · '+v).join(''):'');$('squad-cast-progress').style.width=(playerCast?Math.min(100,100*(b.time-playerCast.startedAt)/playerCast.duration):0)+'%';const charge=fighting?b.charge:s.charge,cost=D.moves[s.build.ultimate].ultimateChargeCost||100,percent=Math.min(100,charge/cost*100);$('squad-charge').textContent=percent>=100?'READY':Math.floor(percent)+'%';
  for(const button of document.querySelectorAll('[data-cast]')){const i=Number(button.dataset.cast),id=i===4?s.build.ultimate:s.build.moves[i],move=fighting?b.getMove(id):D.moves[id],unavailable=!fighting||s.paused||!!b.player.cast||!!b.player.sequence||b.isFrozen(b.player)||Object.entries(move.cost).some(([key,n])=>b.player[key]<n)||i===4&&percent<100||move.squadSupport&&!b.supportTargets(move).length;const resource=Object.hasOwn(move.cost,'mana')?'mana':'stamina',maximum=maxima[resource],lacks=Object.entries(move.cost).some(([key,n])=>actor[key]<n);button.dataset.resource=resource;button.style.setProperty('--liquid',Math.max(0,Math.min(100,100*actor[resource]/maximum))+'%');button.style.setProperty('--demand',Math.min(100,100*(move.cost[resource]||0)/maximum)+'%');button.querySelector('.actual-cost').textContent=U.cost(move);button.setAttribute('aria-disabled',String(unavailable));button.classList.toggle('unavailable',unavailable);button.classList.toggle('insufficient',lacks);button.classList.toggle('casting-selected',playerCast?.moveId===id);if(i===4){button.style.setProperty('--charge',percent+'%');button.classList.toggle('ready',percent>=100);button.classList.toggle('resource-short',percent>=100&&lacks);$('squad-ultimate-warning').textContent=percent>=100&&lacks?'資源不足':'';}}
 }
 function events(){const b=session?.battle;if(b!==activeBattle){activeBattle=b;cursor=0;}if(!b)return;for(const e of b.events.slice(cursor)){if(e.type==='troop-down')message(e.text+' · 等待復歸');if(e.type==='cleave')message('守關者橫掃 · 全體前排承傷');if(e.type==='troop-return')message(e.text);if(e.type==='growth')growthNotice(e);if(e.type==='member-training'&&e.before!==e.after)message(S.config.troops[session.profile.members.find(m=>m.id===e.memberId).type].name+' 本局階級提升 · '+e.after);if(e.type==='loot'){pages.refreshCollection();message('金幣 +'+e.gold+' · 餘光 +'+e.afterlight+(e.skill?' · 技能 '+D.skills[e.skill].name:''));}}cursor=b.events.length;}
 let hudAt=-Infinity,sceneAt=-Infinity,hudTab=null;function frame(now){if(document.hidden){last=now;requestAnimationFrame(frame);return;}const dt=Math.max(0,Math.min(.15,(now-last)/1000));last=now;if(session&&!catchup&&!session.paused&&session.started!==false){session.advance(dt);events(now);if(session.phase==='defeat')result();if(now-saveAt>2000){save();saveAt=now;}}if(now>messageUntil)$('squad-message').textContent='';if(now-hudAt>=100||hudTab!==pages.tab){paintHUD();if(session)pages.tick();hudAt=now;hudTab=pages.tab;}paintGrowth(now);if(now-sceneAt>=1000/30&&$('squad-overlay').hidden&&$('squad-game').dataset.screen!=='page'){art.render(session,draft,S.config);sceneAt=now;}requestAnimationFrame(frame);}
 const pages=new SquadPages.Pages({session:()=>session,busy:()=>!!catchup,ensure:()=>{if(!session){session=new S.Session({started:false});session.paused=true;save();}},close,save,labels,message,reduced:()=>art.reduced,motion:()=>{art.reduced=!art.reduced;savePreferences();},fullscreen:requestView,depart:()=>{const options={build:session.build,members:session.troops.map(t=>t.memberId),formation:session.troops.map(t=>({id:t.memberId,row:t.row,slot:t.slot}))};start(options);}});
 pages.hide();labels();intro(true);requestAnimationFrame(frame);
})();
