/* Persistent lower workspace. Navigation never owns the simulation clock. */
(function(root){
 const S=root.SquadPrototype,D=root.GameData,U=root.SquadPresentation,esc=U.escape,clone=x=>JSON.parse(JSON.stringify(x));
 class Pages{
  constructor(api){this.api=api;this.tab='adventure';this.adventureState=null;this.team='formation';this.collection='moves';this.actor='player';this.selected=null;this.picker=null;this.preview=null;this.filter='all';this.sort='grade';this.showIncompatible=false;this.detail=null;this.scroll=0;this.shop='recruit';this.study='skills';this.shopGrade='C';this.shopResult=null;this.exchangeId=null;
   this.node=document.getElementById('squad-page-content');this.nav=document.getElementById('squad-nav');
   this.node.addEventListener('click',e=>{const button=e.target.closest('[data-squad-action]');if(button&&!button.disabled)this.action(button.dataset);});
   this.node.addEventListener('change',e=>{if(e.target.id==='page-filter'){this.filter=e.target.value;this.render();}if(e.target.id==='page-sort'){this.sort=e.target.value;this.render();}});
   this.nav.addEventListener('click',e=>{const button=e.target.closest('[data-squad-action]');if(button)this.open(button.dataset.tab);});
  }
  session(){return this.api.session();}
  canSkills(){const s=this.session();return s.started===false||s.phase==='defeat';}
  button(action,label,data='',cls=''){return `<button class="${cls}" data-squad-action="${action}" ${data}>${label}</button>`;}
  name(m){return esc(S.config.troops[m.type].name)+' <small>'+S.Members.grade(m)+'</small>';}
  description(item){return item.id==='lucky'?'運氣 +8，提高爆擊機率與爆擊傷害。':item.description||'';}
  title(item){return `<strong>${esc(item.name)}</strong>${item.subtitle?`<small class="spell-subtitle">${esc(item.subtitle)}</small>`:''}`;}
  open(tab){this.api.ensure();this.tab=tab;if(tab==='adventure'&&this.session().phase==='defeat'&&!this.adventureState)this.adventureState='result';this.picker=null;this.detail=null;this.selected=null;this.api.close();this.render();if(tab==='adventure'&&this.session().started===false)this.api.message('尚未出發 · 請在隊伍頁確認配置');}
  hide(){this.tab='adventure';this.adventureState=null;this.picker=null;this.detail=null;this.render();}
  header(){const s=this.session();return `<div class="workspace-heading"><div><small>${s.started===false?'準備遠征':s.phase==='defeat'?'遠征已結束':s.paused?'遠征暫停中':'遠征持續進行'}</small><h2>${{team:'小隊',collection:'收藏',recruit:'募集',settings:'設定'}[this.tab]}</h2></div>${s.started===false||s.phase==='defeat'?this.button('depart','帶隊出發','','primary'):s.paused?this.button('unpause','繼續遠征','','primary'):'<span class="live-badge"><i></i>戰鬥中</span>'}</div>`;}
  showResult(){this.tab='adventure';this.adventureState='result';this.picker=null;this.preview=null;this.detail=null;this.selected=null;this.api.close();this.render();this.node.scrollTop=0;this.node.querySelector('button')?.focus();}
  render(){const content=document.getElementById('squad-workspace'),controls=document.getElementById('squad-controls'),page=document.getElementById('squad-page'),inline=this.tab==='adventure'&&!!this.adventureState;content.dataset.tab=this.tab;content.dataset.adventureState=inline?this.adventureState:'';controls.hidden=this.tab!=='adventure'||inline;page.hidden=this.tab==='adventure'&&!inline;
   this.nav.innerHTML=[['collection','bag','收藏'],['team','party','隊伍'],['adventure','sword','冒險'],['recruit','star','募集'],['settings','gear','設定']].map(([tab,icon,name])=>this.button('nav',`${U.icon(icon)}<span>${name}</span>`,`data-tab="${tab}" aria-current="${this.tab===tab?'page':'false'}"`,tab==='adventure'?'nav-adventure':'')).join('');
   if(this.tab==='adventure'&&!inline)return;
   let html=inline?'':this.header();if(this.picker)html+=this.chooser();else if(inline)html+=this.adventureState==='result'?this.resultPage():this.retryPage();else if(this.detail)html+=this.details();else if(this.tab==='team')html+=this.teamPage();else if(this.tab==='collection')html+=this.collectionPage();else if(this.tab==='recruit')html+=this.recruitPage();else html+=this.settingsPage();
   const top=this.node.scrollTop||0;this.node.innerHTML=html;this.node.scrollTop=top;
  }
  resultPage(){const s=this.session(),r=s.summary(),previous=s.previousResult,units=[{id:'player',name:'隊長'},...s.crew.map(t=>({id:t.id,name:esc(S.config.troops[t.type].name)+' · '+S.Members.grade(s.member(t))}))];
   return `<section class="adventure-outcome"><div class="outcome-scroll"><header class="outcome-heading"><small>戰敗 · 隊長倒下</small><h2>冒險已經結束</h2><p>第 ${r.cycle} 輪 · 第 ${r.battleNumber} 場</p></header>${r.boss?`<p class="near-victory">還差 ${r.enemyRemaining}% 擊敗${esc(r.enemyName)}</p>`:''}<div class="squad-result"><div><strong>${r.kills}</strong><span>擊敗敵人</span></div><div><strong>${r.bossKills}</strong><span>擊敗 Boss</span></div><div><strong>${r.battleNumber}</strong><span>最高推進場次</span></div><div><strong>${r.time} 秒</strong><span>本次戰鬥時間</span></div></div>${previous?`<p class="run-comparison">上次第 ${previous.battleNumber} 場 → 本次第 ${r.battleNumber} 場（${r.battleNumber-previous.battleNumber>=0?'+':''}${r.battleNumber-previous.battleNumber}）</p>`:''}<details class="battle-review"><summary>本次收穫 · 永久保留</summary><p>金幣 +${s.runLoot.gold} · 餘光 +${s.runLoot.afterlight}</p>${Object.entries(s.runLoot.skills).map(([id,count])=>`<p>${esc(D.skills[id]?.name||id)} ×${count}</p>`).join('')||'<p class="page-hint">本次沒有技能掉落。</p>'}</details>${Object.entries(s.runLoot.moves||{}).map(([id,n])=>`<p class="page-hint">招式：${esc(D.moves[id]?.name||id)} ×${n}</p>`).join('')}<details class="battle-review"><summary>隊員培養</summary>${s.profile.members.filter(m=>s.trainingThisRun[m.id]).map(m=>`<p>${this.name(m)} · 本次 +${s.trainingThisRun[m.id]} 培養經驗</p>`).join('')||'<p class="page-hint">本次尚未取得培養經驗。</p>'}</details><details class="battle-review"><summary>小隊戰績</summary><table><thead><tr><th>成員</th><th>傷害</th><th>治療</th><th>承傷</th><th>倒下</th></tr></thead><tbody>${units.map(u=>{const m=s.stats.members[u.id];return `<tr><th>${u.name}</th><td>${Math.round(m.damage)}</td><td>${Math.round(m.healing)}</td><td>${Math.round(m.taken)}</td><td>${u.id==='player'?'1':m.downs}</td></tr>`;}).join('')}</tbody></table><p>手動施放 ${s.stats.casts-s.stats.autoUltimates} 次 · 自動必殺 ${s.stats.autoUltimates} 次</p></details></div><footer class="outcome-footer">${this.button('retry-prepare','再次戰鬥','','primary')}</footer></section>`;
  }
  retryPage(){const s=this.session(),actors=[{id:'player',type:'captain'},...s.troops.map(t=>({id:t.memberId,type:t.type}))],captain=this.actor==='player',member=captain?null:s.profile.members.find(m=>m.id===this.actor),skills=captain?s.build.talents:member.skills,count=captain?4:s.slots(member).skills;
   return `<section class="adventure-outcome"><div class="outcome-scroll"><header class="outcome-heading retry-heading"><small>下一次冒險</small><h2>重新搭配技能</h2><p>可以重新搭配已收藏技能，準備好後開始戰鬥。</p></header><div class="actor-strip">${actors.map(a=>this.button('actor',`${U.portrait(a.type)}<span>${a.id==='player'?'隊長':S.config.troops[a.type].name}</span>`,`data-id="${a.id}" aria-pressed="${a.id===this.actor}"`)).join('')}</div><div class="section-heading"><h3>${captain?'隊長':this.name(member)}的技能</h3><span>${skills.length} / ${count}</span></div><div class="slot-grid">${Array.from({length:count},(_,i)=>this.button('slot',`<small>技能 ${i+1}</small>${skills[i]?this.title(D.skills[skills[i]]):'<strong>＋</strong><span>選擇技能</span>'}`,`data-kind="skills" data-slot="${i}"`,'loadout-slot '+(skills[i]?'equipped':'empty'))).join('')}</div><p class="page-hint">金幣、餘光、收藏與隊員培養保留；隊長本次成長會從頭開始。可沿用目前搭配。</p></div><footer class="outcome-footer">${this.button('retry-start','開始戰鬥','','primary')}</footer></section>`;
  }
  teamPage(){return `<div class="page-tabs">${this.button('team-tab','站位',`data-tab="formation" aria-pressed="${this.team==='formation'}"`)}${this.button('team-tab','配置',`data-tab="config" aria-pressed="${this.team==='config'}"`)}</div>`+(this.team==='formation'?this.formation():this.configuration());}
  formation(){const s=this.session();const cell=(row,slot)=>{const t=s.troops.find(t=>t.row===row&&t.slot===slot),m=t?s.member(t):null;return this.button('position',t?`${U.portrait(t.type)}<strong>${this.name(m)}</strong><span id="page-hp-${t.id}">${this.health(t)}</span>`:`<b>＋</b><span>空位</span>`,`data-row="${row}" data-slot="${slot}" ${t?'data-id="'+t.memberId+'"':''} aria-pressed="${t?.memberId===this.selected}"`,t?'position filled':'position');};
   return `<div class="formation-head"><span>隊長固定在左側</span><b>${s.troops.length} / 3</b></div><div class="formation-board"><div class="formation-captain">${U.portrait('captain')}<span>隊長</span></div><div class="formation-column"><small>後排</small>${[0,1,2].map(i=>cell('back',i)).join('')}</div><div class="formation-column"><small>前排</small>${[0,1,2].map(i=>cell('front',i)).join('')}</div><div class="enemy-direction">敵<br>人<br>←</div></div><p class="page-hint">${this.selected?'再點一個位置移動或互換。':'點隊員後選位置；點空位加入隊員。可單人出發。'}</p>${this.selected?this.button('remove-member','移至待命',`data-id="${this.selected}"`):''}<details class="page-explain"><summary>受擊與換人規則</summary><p>一般攻擊隨機命中一名存活前排；沒有前排才攻擊後排，所有隊員倒下才打隊長。連擊鎖定同一目標。特殊攻擊依敵人讀條提示。</p><p>更換不回滿 HP、不重置狀態與回場 CD；待命隊員不攻擊。倒下後原位回場。</p></details>${this.button('bench','待命隊員 · '+(s.crew.length-s.troops.length)+' 人')}`;
  }
  health(t){return t.hp>0?Math.ceil(t.hp)+' / '+Math.round(t.maxHp):'回場 '+Math.ceil(Math.max(0,t.reviveAt-this.session().time))+' 秒';}
  configuration(){const s=this.session(),actors=[{id:'player',type:'captain'},...s.troops.map(t=>({id:t.memberId,type:t.type}))];if(this.actor!=='player'&&!s.profile.members.some(m=>m.id===this.actor))this.actor='player';const captain=this.actor==='player',m=s.profile.members.find(m=>m.id===this.actor),t=s.crew.find(t=>t.memberId===this.actor),stats=captain?s.maxStats():s.memberStats(m),slots=captain?{moves:4,skills:4}:s.slots(m),moves=captain?s.build.moves:m.moves,skills=captain?s.build.talents:m.skills;
   const slot=(kind,i,id,label)=>this.button('slot',`<small>${label}</small>${id?this.title(D[kind][id]):'<strong>＋</strong><span>選擇'+(kind==='moves'?'招式':'技能')+'</span>'}`,`data-kind="${kind}" data-slot="${i}"`, 'loadout-slot '+(id?'equipped':'empty'));
   return `<div class="actor-strip">${actors.map(a=>this.button('actor',`${U.portrait(a.type)}<span>${a.id==='player'?'隊長':S.config.troops[a.type].name}</span>`,`data-id="${a.id}" aria-pressed="${a.id===this.actor}"`)).join('')}${!captain&&!actors.some(a=>a.id===this.actor)?this.button('actor',`${U.portrait(m.type)}<span>待命 · ${this.name(m)}</span>`,`data-id="${m.id}" aria-pressed="true"`):''}</div><article class="actor-summary">${U.portrait(captain?'captain':m.type)}<div><h3>${captain?'遠征隊長':this.name(m)}</h3><p>HP ${Math.round(stats.hp)}${captain?' · SP '+Math.round(stats.stamina)+' · MP '+Math.round(stats.mana):' · 攻擊 '+stats.attack}</p><small>${captain?'由你施放招式':'自動輪流出招 · 不消耗 MP／SP'}</small><details><summary>能力與特性</summary><p>${captain?'敏捷 '+stats.agility+' · 運氣 '+stats.luck:esc(S.config.troops[m.type].description)+'<br>基礎出手間隔 '+stats.interval.toFixed(2)+' 秒<br>'+slots.moves+' 招式欄 · '+slots.skills+' 技能欄'}</p></details></div></article><div class="section-heading"><h3>${captain?'招式與必殺':'自動招式'}</h3><span>可隨時更換</span></div>${captain?`<div class="config-diamond">${moves.map((id,i)=>`<div class="config-dir-${i}">${slot('moves',i,id,'招式 '+'ABCD'[i])}</div>`).join('')}<div class="config-ultimate">${slot('moves',4,s.build.ultimate,'必殺')}</div></div>`:`<div class="slot-grid">${Array.from({length:slots.moves},(_,i)=>slot('moves',i,moves[i],'招式 '+(i+1))).join('')}</div><p class="page-hint">${m.type==='striker'?'可裝備物理招式':m.type==='guard'?'可裝備物理招式與前排護盾':'可裝備魔法與治療輔助招式'}。空欄使用兵種普攻；已裝備招式依攻擊力計算傷害、依速度讀條。</p>`}<div class="section-heading"><h3>被動技能</h3><span>${this.canSkills()?'出發前配置':'本次遠征已鎖定'}</span></div><div class="slot-grid">${Array.from({length:slots.skills},(_,i)=>slot('skills',i,skills[i],'技能 '+(i+1))).join('')}</div><p class="page-hint">技能僅能在出發前或結算後更換。暫停不會解除配置鎖定。</p>`;
  }
  collectionPage(){const s=this.session(),p=s.profile;return `<div class="wallet-compact"><span>${U.icon('coin')}${p.gold.toLocaleString()}</span><span>${U.icon('star')}${p.afterlight.toLocaleString()}</span></div><div class="page-tabs">${[['moves','招式'],['skills','技能'],['members','隊員']].map(([id,label])=>this.button('collection-tab',label,`data-tab="${id}" aria-pressed="${this.collection===id}"`)).join('')}</div>`+(this.collection==='members'?this.memberCollection():this.itemList(this.collection,false));}
  memberCollection(){const s=this.session();return `<p class="page-hint">隊員永久收藏；同兵種的每位隊員獨立培養。</p><div class="collection-grid">${Object.keys(S.config.troops).map(type=>{const owned=s.profile.members.filter(m=>m.type===type);return this.button('member-detail',`${U.portrait(type)}<strong>${esc(S.config.troops[type].name)}</strong><small>${owned.length?'已收藏 '+owned.length+' 人':'尚未招募'}</small>`,`data-type="${type}"`,'collection-card');}).join('')}</div>`;}
  memberList(records){const s=this.session();return records.map(m=>{const p=S.Members.progress(m),d=s.memberStats(m),active=s.troops.find(t=>t.memberId===m.id);return `<article class="member-record"><div class="member-card-top">${U.portrait(m.type)}<header><strong>${this.name(m)}</strong><span>${active?(active.row==='front'?'前排':'後排')+' · 出戰中':'待命'} · #${m.id.slice(7)}</span></header></div><p>HP <b>${d.hp}</b> · 攻擊 <b>${d.attack}</b> · 間隔 ${d.interval.toFixed(2)}s</p><div class="training-rail"><i style="width:${p.ratio*100}%"></i></div><small>${p.next?'前往 '+p.next+' · '+p.current+' / '+p.required:'培養完成'}</small>${this.button('member-config','配置招式與技能',`data-id="${m.id}"`)}</article>`;}).join('');}
  recruitPage(){const s=this.session(),r=S.config.collectionRules,w=r.rarityWeights,kind=this.study,pool=kind==='moves'?S.config.moves:S.config.loop.rewards.skillPool,available=pool.filter(id=>!(s.profile[kind][id]>0)&&(D[kind][id].powerGrade||'C')===this.shopGrade),item=this.exchangeId?D[kind][this.exchangeId]:null;
   const result=this.shopResult?`<article class="selection-preview" role="status"><small>${this.shopResult.duplicate?'重複收藏':'新收藏'}</small><h3>${esc(this.shopResult.name)}</h3><p>${esc(this.shopResult.text)}</p></article>`:'';
   return `<div class="wallet-compact"><span>金幣 ${s.profile.gold}</span><span>餘光 ${s.profile.afterlight}</span><span>研習 ${s.profile.researchPoints}</span></div><div class="page-tabs">${[['recruit','招募'],['research','研習']].map(([id,label])=>this.button('shop-tab',label,`data-tab="${id}" aria-pressed="${this.shop===id}"`)).join('')}</div>${result}`+(this.shop==='recruit'?`<section class="recruit-banner"><h3>旅途中的夥伴</h3><p>盾衛／劍士／祈願者各 1/3。每位隊員永久保留，由該稀有度的 − 開始培養。同兵種也會成為獨立隊員，不折算點數。</p>${this.button('recruit-draw',`招募一名 · ${r.recruitCost} 金幣`,s.profile.gold<r.recruitCost?'disabled':'','primary')}</section><p class="page-hint">稀有度機率：${Object.entries(w).map(([g,n])=>g+' '+n+'%').join(' · ')}</p><h3>已加入的隊員 · ${s.profile.members.length} 人</h3>${this.memberList(s.profile.members)}`:`<div class="page-tabs">${[['moves','招式'],['skills','技能']].map(([id,label])=>this.button('study-tab',label,`data-kind="${id}" aria-pressed="${kind===id}"`)).join('')}</div><section class="recruit-banner"><h3>${kind==='moves'?'招式':'技能'}研習</h3><p>新內容永久收藏；重複轉為研習點數。招式可隨時裝備，技能於出發前或結算後配置。</p>${this.button('research-draw',`研習一次 · ${r.researchCost} 餘光`,s.profile.afterlight<r.researchCost?'disabled':'','primary')}</section><p class="page-hint">稀有度：${Object.entries(w).map(([g,n])=>g+' '+n+'%').join(' · ')}。各階內等機率；缺少某階時，按現有階權重重新分配。<br>重複所得點數：${Object.entries(r.duplicatePoints).map(([g,n])=>g+' '+n).join(' · ')}</p><h3>指定收藏兌換</h3><div class="page-tabs">${Object.keys(w).map(g=>this.button('exchange-grade',g,`data-grade="${g}" aria-pressed="${g===this.shopGrade}"`)).join('')}</div><p class="page-hint">${this.shopGrade} 級兌換：${r.exchangeCosts[this.shopGrade]} 研習點數 · 僅顯示未收藏內容。</p>${item?`<article class="selection-preview">${this.title(item)}<p>${esc(this.description(item))}</p>${this.button('exchange-confirm',`確認兌換 · ${r.exchangeCosts[item.powerGrade||'C']} 點`,`data-id="${item.id}" ${s.profile.researchPoints<r.exchangeCosts[item.powerGrade||'C']?'disabled':''}`,'primary')}</article>`:''}<div class="collection-grid">${available.map(id=>this.button('exchange-preview',this.title(D[kind][id]),`data-id="${id}"`,'collection-card')).join('')||'<p>此階內容已全數收藏。</p>'}</div>`);
  }
  settingsPage(){return `<div class="settings-card"><div><strong>減少動態演出</strong><p>不影響戰鬥速度。</p></div>${this.button('motion',this.api.reduced()?'開啟':'關閉',`aria-pressed="${this.api.reduced()}"`,'setting-toggle')}</div><div class="settings-card"><div><strong>直式全螢幕</strong><p>支援時鎖定直式。</p></div>${this.button('fullscreen','開啟')}</div><div class="settings-card"><div><strong>自動施放必殺</strong><p>普通招式仍由你操作。</p></div>${this.button('auto',this.session().autoUltimate?'開啟':'關閉',`aria-pressed="${this.session().autoUltimate}"`,'setting-toggle')}</div><div class="connection-card">${U.icon('check')}<div><strong>進度自動儲存</strong><p>${esc(root.GameOffline?.status||'以 HTTPS 開啟，可下載完整離線資源。')}</p></div></div><small class="version-note">AFTERLIGHT · v${D.release.version}<br>${D.release.date}</small><p class="page-hint">切換分頁不會暫停；使用上方暫停按鈕才會停止戰鬥。</p>`;}
  itemList(kind,picking){const s=this.session(),owned=s.profile[kind],catalog=kind==='moves'?S.config.moves:S.config.loop.rewards.skillPool,member=this.actor==='player'?null:s.profile.members.find(m=>m.id===this.actor),ids=catalog.filter(id=>D[kind][id]&&(!picking||kind!=='moves'||(!member&&this.picker?.slot===4)||D.moves[id].kind==='normal'));let list=ids.filter(id=>!picking||owned[id]>0);
   const compatible=id=>!picking||!member||s.compatible(member,id,kind);if(picking&&!this.showIncompatible)list=list.filter(compatible);if(this.filter!=='all')list=list.filter(id=>kind==='moves'?D.moves[id].damageType===this.filter:D.skills[id].category===this.filter);const grades={C:0,B:1,A:2,S:3,SS:4};list.sort((a,b)=>this.sort==='name'?D[kind][a].name.localeCompare(D[kind][b].name,'zh-Hant'):this.sort==='type'?String(D[kind][a].damageType||D[kind][a].category).localeCompare(String(D[kind][b].damageType||D[kind][b].category)): (grades[D[kind][b].powerGrade||'C']-grades[D[kind][a].powerGrade||'C'])||D[kind][a].name.localeCompare(D[kind][b].name,'zh-Hant'));
   const categories=kind==='moves'?[['physical','物理'],['magic','魔法']]:[...new Set(ids.map(id=>D.skills[id].category||'legacy'))].map(c=>[c,{legacy:'能力',survival:'生存',special:'特殊',resource:'資源'}[c]||c]);
   return `<div class="list-toolbar"><span>${Object.keys(owned).filter(id=>ids.includes(id)&&owned[id]>0).length} / ${ids.length}</span><select id="page-filter" aria-label="類型"><option value="all" ${this.filter==='all'?'selected':''}>所有類型</option>${categories.map(([id,name])=>`<option value="${id}" ${this.filter===id?'selected':''}>${name}</option>`).join('')}</select><select id="page-sort" aria-label="排列方式">${[['grade','稀有度'],['type','類型'],['name','名稱']].map(([id,name])=>`<option value="${id}" ${this.sort===id?'selected':''}>${name}</option>`).join('')}</select></div>${picking&&member?this.button('incompatible',this.showIncompatible?'隱藏不相容':'顯示不相容'):''}<div class="collection-grid">${list.map(id=>{const item=D[kind][id],known=owned[id]>0,ok=compatible(id);return this.button(picking?'preview':'item-detail',`${U.icon(known?item.icon:'lock')}<em class="item-grade">${known?item.powerGrade||'C':'?'}</em>${known?this.title(item):'<strong>未知'+(kind==='moves'?'招式':'技能')+'</strong>'}<small>${!known?'尚未收藏':!ok?'此隊員不相容':kind==='moves'?(picking&&member?'隊員無消耗':U.cost(item)):'永久收藏 ×'+owned[id]}</small>`,`data-id="${id}" data-kind="${kind}" ${!known?'disabled':''}`, 'collection-card '+(!ok?'incompatible':''));}).join('')||'<p class="page-hint">沒有符合條件的收藏。</p>'}</div>`;
  }
  chooser(){const s=this.session(),p=this.picker;if(p.kind==='members')return this.button('picker-back','← 返回站位')+`<h3>選擇入隊成員</h3>`+s.profile.members.map(m=>this.button('choose-member',`${U.portrait(m.type)}<span>${this.name(m)}<small>${s.troops.some(t=>t.memberId===m.id)?'出戰中 · 互換位置':'待命'}</small></span>`,`data-id="${m.id}"`,'member-choice')).join('');
   const item=this.preview?D[p.kind][this.preview]:null,m=this.actor==='player'?null:s.profile.members.find(m=>m.id===this.actor),compatible=!m||!item||s.compatible(m,item.id,p.kind),locked=p.kind==='skills'&&!this.canSkills();
   return this.button('picker-back',this.tab==='adventure'&&this.adventureState==='retry'?'← 返回技能搭配':'← 返回配置')+`<h3>${p.kind==='moves'?'選擇招式':'選擇技能'}</h3>${locked?'<p class="config-lock">本次技能已鎖定；可查看，結算後才能更換。</p>':''}${item?`<article class="selection-preview">${this.title(item)}<p>${esc(this.description(item))}</p>${p.kind==='moves'?`<p>${esc(U.effects(item))}</p><small>${m?'隊員無消耗 · 讀條 '+this.memberCast(m,item).toFixed(2)+' 秒':U.cost(item)}</small>`:''}${!compatible?'<p class="config-lock">此兵種無法裝備；'+(p.kind==='skills'?'隊員無 MP／SP，資源與隊長成長技能不適用。':'招式類型不相容。')+'</p>':''}${this.button('equip','確認裝備',`data-id="${this.preview}" ${locked||!compatible?'disabled':''}`,'primary')}</article>`:''}${p.kind==='skills'||m?this.button('unequip','清空此欄',locked?'disabled':''):''}${this.itemList(p.kind,true)}`;
  }
  memberCast(m,move){const s=this.session(),t=s.crew.find(t=>t.memberId===m.id),agility=10+m.skills.reduce((n,id)=>n+(D.skills[id]?.modifiers?.agility||0),0);return s.phase==='fighting'&&s.battle?s.battle.castDuration(s.battle.getMove(move.id,t),t):Math.max(.5,move.attackTime/100*s.memberStats(m).interval*10/agility);}
  details(){const d=this.detail;if(d.type)return this.button('detail-back','← 返回收藏')+`<h3>${esc(S.config.troops[d.type].name)}</h3>`+this.memberList(this.session().profile.members.filter(m=>m.type===d.type));const item=D[d.kind][d.id];return this.button('detail-back','← 返回收藏')+`<article class="selection-preview">${this.title(item)}<p>${esc(this.description(item))}</p>${d.kind==='moves'?`<p>${esc(U.effects(item))}</p><small>${U.cost(item)}</small>`:''}</article><h3>裝備給</h3>${this.button('detail-equip','隊長配置',`data-id="player" data-kind="${d.kind}"`)}${this.session().troops.map(t=>this.button('detail-equip',this.name(this.session().member(t)),`data-id="${t.memberId}" data-kind="${d.kind}" ${!this.session().compatible(this.session().member(t),d.id,d.kind)?'disabled':''}`)).join('')}${d.kind==='skills'&&!this.canSkills()?'<p class="config-lock">遠征中的技能無法更換。</p>':''}`;}
  action(d){const s=this.session();try{
   if(d.squadAction==='retry-prepare'){if(s.phase!=='defeat')return;this.tab='adventure';this.adventureState='retry';this.actor='player';this.picker=null;this.detail=null;this.node.scrollTop=0;}
   else if(d.squadAction==='retry-start'){if(s.phase!=='defeat'||this.adventureState!=='retry'||this.picker)return;this.api.depart();this.hide();return;}
   else if(d.squadAction==='nav'){this.open(d.tab);return;}
   if(d.squadAction==='shop-tab'){this.shop=d.tab;this.shopResult=null;this.exchangeId=null;}
   else if(d.squadAction==='study-tab'){this.study=d.kind;this.shopResult=null;this.exchangeId=null;}
   else if(d.squadAction==='exchange-grade'){this.shopGrade=d.grade;this.exchangeId=null;}
   else if(d.squadAction==='exchange-preview'){this.exchangeId=d.id;}
   else if(d.squadAction==='recruit-draw'){const m=s.recruit();this.shopResult={name:S.config.troops[m.type].name+' '+S.Members.grade(m),text:'已加入永久名冊，可至隊伍頁安排站位。'};this.api.save();}
   else if(d.squadAction==='research-draw'||d.squadAction==='exchange-confirm'){const result=d.squadAction==='research-draw'?s.research(this.study):s.exchange(this.study,d.id);this.shopResult={...result,name:D[this.study][result.id].name,text:result.duplicate?'已收藏，獲得 '+result.points+' 研習點數。':'已永久收藏，可在配置頁查看。'};this.exchangeId=null;this.api.save();}
   else if(d.squadAction==='team-tab'){this.team=d.tab;this.selected=null;}
   else if(d.squadAction==='collection-tab'){this.collection=d.tab;this.filter='all';}
   else if(d.squadAction==='actor'){this.actor=d.id;}
   else if(d.squadAction==='position'){if(this.selected){s.placeMember(this.selected,d.row,Number(d.slot));this.selected=null;this.api.save();}else if(d.id)this.selected=d.id;else this.picker={kind:'members',row:d.row,slot:Number(d.slot)};}
   else if(d.squadAction==='remove-member'){s.removeMember(d.id);this.selected=null;this.api.save();}
   else if(d.squadAction==='bench'){this.collection='members';this.tab='collection';}
   else if(d.squadAction==='choose-member'){s.placeMember(d.id,this.picker.row,this.picker.slot);this.picker=null;this.api.save();}
   else if(d.squadAction==='member-config'){this.tab='team';this.team='config';this.actor=d.id;this.detail=null;}
   else if(d.squadAction==='slot'){this.picker={kind:d.kind,slot:Number(d.slot)};this.preview=this.pendingItem?.kind===d.kind?this.pendingItem.id:null;this.pendingItem=null;this.filter='all';}
   else if(d.squadAction==='picker-back'){this.picker=null;this.preview=null;}
   else if(d.squadAction==='preview'){this.preview=d.id;}
   else if(d.squadAction==='incompatible'){this.showIncompatible=!this.showIncompatible;}
   else if(d.squadAction==='equip'||d.squadAction==='unequip'){this.equip(d.squadAction==='equip'?d.id:null);this.picker=null;this.api.save();this.api.labels();}
   else if(d.squadAction==='item-detail'){this.detail={kind:d.kind,id:d.id};}
   else if(d.squadAction==='member-detail'){this.detail={type:d.type};}
   else if(d.squadAction==='detail-back')this.detail=null;
   else if(d.squadAction==='detail-equip'){this.pendingItem={...this.detail};this.actor=d.id;this.tab='team';this.team='config';this.detail=null;}
   else if(d.squadAction==='depart'){this.api.depart();this.hide();return;}
   else if(d.squadAction==='unpause'){s.paused=false;this.api.save();}
   else if(d.squadAction==='motion')this.api.motion();
   else if(d.squadAction==='fullscreen')this.api.fullscreen();
   else if(d.squadAction==='auto'){s.autoUltimate=!s.autoUltimate;this.api.save();}
   this.render();
  }catch(e){this.api.message(e.message);}}
  equip(id){const s=this.session(),p=this.picker,member=this.actor==='player'?null:s.profile.members.find(m=>m.id===this.actor);if(member){const moves=clone(member.moves),skills=clone(member.skills),list=p.kind==='moves'?moves:skills;if(id)list[p.slot]=id;else list.splice(p.slot,1);s.setMemberLoadout(member.id,moves.filter(Boolean),skills.filter(Boolean));}else if(p.kind==='skills'){const ids=clone(s.build.talents);if(id)ids[p.slot]=id;else ids.splice(p.slot,1);s.setSkills(ids.filter(Boolean));}else{if(!id)throw Error('隊長需保留四招與必殺');const build=clone(s.build);if(p.slot===4)build.ultimate=id;else build.moves[p.slot]=id;s.setLoadout(build);}}
  refreshCollection(){if(!this.picker&&!this.detail&&['collection','recruit'].includes(this.tab))this.render();}
  tick(){if(this.tab==='team'&&this.team==='formation'&&!this.picker)for(const t of this.session().troops){const node=document.getElementById('page-hp-'+t.id);if(node)node.textContent=this.health(t);}}
 }
 root.SquadPages={Pages};
})(globalThis);
