/* Portrait pages cover combat visually; navigation never owns its clock. */
(function(root){
 const S=root.SquadPrototype,D=root.GameData,U=root.SquadPresentation,esc=U.escape,clone=x=>JSON.parse(JSON.stringify(x));
 class Pages{
  constructor(api){this.api=api;this.tab='adventure';this.adventureState=null;this.team='formation';this.collection='moves';this.actor='player';this.selected=null;this.picker=null;this.preview=null;this.filter='all';this.sort='grade';this.showIncompatible=false;this.detail=null;this.scroll=0;this.shop='recruit';this.study='skills';this.shopGrade='C';this.shopResult=null;this.exchangeId=null;
   this.node=document.getElementById('squad-page-content');this.nav=document.getElementById('squad-nav');this.memberView='config';this.memberReturn=null;
   document.getElementById('squad-battle-strip').addEventListener('click',()=>this.open('adventure'));
   this.node.addEventListener('click',e=>{const button=e.target.closest('[data-squad-action]');if(button&&!button.disabled)this.action(button.dataset);});
   this.node.addEventListener('change',e=>{if(e.target.id==='page-filter'){this.filter=e.target.value;this.render();}if(e.target.id==='page-sort'){this.sort=e.target.value;this.render();}});
   this.nav.addEventListener('click',e=>{const button=e.target.closest('[data-squad-action]');if(button)this.open(button.dataset.tab);});
  }
  session(){return this.api.session();}
  canSkills(){const s=this.session();return s.started===false||s.phase==='defeat';}
  button(action,label,data='',cls=''){return `<button class="${cls}" data-squad-action="${action}" ${data}>${label}</button>`;}
  name(m){return esc(S.config.troops[m.type].name)+' <small>'+S.Members.grade(m)+'</small>';}
  description(item,member=false){return (D.skills[item.id]===item?S.Skills.description(item,member):item.description||'').replace(/敏捷/g,'速度');}
  title(item){return `<strong>${esc(item.name)}</strong>${item.subtitle?`<small class="spell-subtitle">${esc(item.subtitle)}</small>`:''}`;}
  open(tab){if(this.api.busy?.())return;this.api.ensure();this.tab=tab;if(tab==='adventure'&&this.session().phase==='defeat'&&!this.adventureState)this.adventureState='result';this.picker=null;this.detail=null;this.selected=null;this.node.scrollTop=0;this.api.close();this.render();if(tab==='adventure'&&this.session().started===false)this.api.message('尚未出發 · 請在隊伍頁確認配置');}
  hide(){this.tab='adventure';this.adventureState=null;this.picker=null;this.detail=null;this.render();}
  header(){const s=this.session();return `<div class="workspace-heading"><div><small>${s.started===false?'準備遠征':s.phase==='defeat'?'遠征已結束':s.paused?'遠征暫停中':'遠征持續進行'}</small><h2>${{team:'小隊',collection:'收藏',recruit:'募集',settings:'設定'}[this.tab]}</h2></div>${s.started===false||s.phase==='defeat'?this.button('depart','帶隊出發','','primary'):s.paused?this.button('unpause','繼續遠征','','primary'):'<span class="live-badge"><i></i>戰鬥中</span>'}</div>`;}
  showResult(){this.tab='adventure';this.adventureState='result';this.picker=null;this.preview=null;this.detail=null;this.selected=null;this.api.close();this.render();this.node.scrollTop=0;this.node.querySelector('button')?.focus();}
  render(){const content=document.getElementById('squad-workspace'),controls=document.getElementById('squad-controls'),page=document.getElementById('squad-page'),inline=this.tab==='adventure'&&!!this.adventureState,full=this.tab!=='adventure'||!!this.picker;content.dataset.tab=this.tab;content.dataset.adventureState=inline?this.adventureState:'';content.dataset.view=this.picker?'picker':'page';document.getElementById('squad-game').dataset.screen=full?'page':'adventure';document.getElementById('squad-battle-strip').hidden=!full;document.getElementById('squad-page-notice').hidden=!full;for(const id of ['squad-top','squad-scene','squad-vitals'])document.getElementById(id).inert=full;controls.hidden=this.tab!=='adventure'||inline;page.hidden=this.tab==='adventure'&&!inline;
   this.nav.innerHTML=[['collection','bag','收藏'],['team','party','隊伍'],['adventure','sword','冒險'],['recruit','star','募集'],['settings','gear','設定']].map(([tab,icon,name])=>this.button('nav',`${U.icon(icon)}<span>${name}</span>`,`data-tab="${tab}" aria-current="${this.tab===tab?'page':'false'}"`,tab==='adventure'?'nav-adventure':'')).join('');
   if(this.tab==='adventure'&&!inline){this.node.innerHTML='';return;}
   let html=inline||this.picker?'':this.header();if(this.picker)html+=this.chooser();else if(inline)html+=this.adventureState==='result'?this.resultPage():this.retryPage();else if(this.detail)html+=this.details();else if(this.tab==='team')html+=this.teamPage();else if(this.tab==='collection')html+=this.collectionPage();else if(this.tab==='recruit')html+=this.recruitPage();else html+=this.settingsPage();
   const top=this.node.scrollTop||0;this.node.innerHTML=html;this.node.scrollTop=this.picker?0:top;this.tick();
  }
  resultPage(){const s=this.session(),r=s.summary(),previous=s.previousResult,units=[{id:'player',name:'隊長'},...s.crew.map(t=>({id:t.id,name:esc(S.config.troops[t.type].name)+' · '+S.Members.grade(s.member(t))}))];
   return `<section class="adventure-outcome"><div class="outcome-scroll"><header class="outcome-heading"><small>戰敗 · 隊長倒下</small><h2>冒險已經結束</h2><p>第 ${r.cycle} 輪 · 第 ${r.battleNumber} 場</p></header>${this.offlineSummary()}${r.boss?`<p class="near-victory">還差 ${r.enemyRemaining}% 擊敗${esc(r.enemyName)}</p>`:''}<div class="squad-result"><div><strong>${r.kills}</strong><span>擊敗敵人</span></div><div><strong>${r.bossKills}</strong><span>擊敗 Boss</span></div><div><strong>${r.battleNumber}</strong><span>最高推進場次</span></div><div><strong>${r.time} 秒</strong><span>本次戰鬥時間</span></div></div>${previous?`<p class="run-comparison">上次第 ${previous.battleNumber} 場 → 本次第 ${r.battleNumber} 場（${r.battleNumber-previous.battleNumber>=0?'+':''}${r.battleNumber-previous.battleNumber}）</p>`:''}<details class="battle-review"><summary>本次收穫 · 永久保留</summary><p>金幣 +${s.runLoot.gold} · 餘光 +${s.runLoot.afterlight}</p>${Object.entries(s.runLoot.skills).map(([id,count])=>`<p>${esc(D.skills[id]?.name||id)} ×${count}</p>`).join('')||'<p class="page-hint">本次沒有技能掉落。</p>'}</details>${Object.entries(s.runLoot.moves||{}).map(([id,n])=>`<p class="page-hint">招式：${esc(D.moves[id]?.name||id)} ×${n}</p>`).join('')}<details class="battle-review"><summary>隊員培養</summary>${s.profile.members.filter(m=>s.trainingThisRun[m.id]).map(m=>`<p>${this.name(m)} · 本次 +${s.trainingThisRun[m.id]} 培養經驗（下局重置）</p>`).join('')||'<p class="page-hint">本次尚未取得培養經驗。</p>'}</details><details class="battle-review"><summary>小隊戰績</summary><table><thead><tr><th>成員</th><th>傷害</th><th>治療</th><th>承傷</th><th>倒下</th></tr></thead><tbody>${units.map(u=>{const m=s.stats.members[u.id];return `<tr><th>${u.name}</th><td>${Math.round(m.damage)}</td><td>${Math.round(m.healing)}</td><td>${Math.round(m.taken)}</td><td>${u.id==='player'?'1':m.downs}</td></tr>`;}).join('')}</tbody></table><p>手動施放 ${s.stats.casts-s.stats.autoUltimates-(s.stats.autoFirstCasts||0)} 次 · 自動招式 A ${s.stats.autoFirstCasts||0} 次 · 自動必殺 ${s.stats.autoUltimates} 次</p></details></div><footer class="outcome-footer">${this.button('retry-prepare','再次戰鬥','','primary')}</footer></section>`;
  }
  offlineSummary(){const r=this.session()?.offlineReport;if(!r)return '';const A=root.SquadAway;return `<section class="away-summary"><p>離線 ${A.duration(r.awaySeconds)} · 實際冒險 ${A.duration(r.adventureSeconds)}${r.defeated?' · 隊長倒下後停止':''}</p><div class="squad-result"><div><strong>+${r.gold}</strong><span>金幣</span></div><div><strong>+${r.afterlight}</strong><span>餘光</span></div><div><strong>${r.kills}</strong><span>擊敗敵人</span></div><div><strong>${r.bossKills}</strong><span>擊敗 Boss</span></div></div><p>${r.gradeBefore} → ${r.gradeAfter}${r.levelAfter>r.levelBefore?' · 能力提升 '+(r.levelAfter-r.levelBefore)+' 次':''}${r.researchPoints?' · 研習點數 +'+r.researchPoints:''}</p>${['moves','skills'].map(kind=>Object.entries(r[kind]).map(([id,n])=>`<p class="away-item">${kind==='moves'?'招式':'技能'} · ${esc(D[kind][id]?.name||id)}${D[kind][id]?.subtitle?'（'+esc(D[kind][id].subtitle)+'）':''} ×${n}</p>`).join('')).join('')}</section>`;}
  retryPage(){const s=this.session(),actors=[{id:'player',type:'captain'},...s.troops.map(t=>({id:t.memberId,type:t.type}))],captain=this.actor==='player',member=captain?null:s.profile.members.find(m=>m.id===this.actor),skills=captain?s.build.talents:member.skills,count=captain?4:s.slots(member).skills;
   return `<section class="adventure-outcome"><div class="outcome-scroll"><header class="outcome-heading retry-heading"><small>下一次冒險</small><h2>重新搭配技能</h2><p>可以重新搭配已收藏技能，準備好後開始戰鬥。</p></header><div class="actor-strip">${actors.map(a=>this.button('actor',`${U.portrait(a.type)}<span>${a.id==='player'?'隊長':S.config.troops[a.type].name}</span>`,`data-id="${a.id}" aria-pressed="${a.id===this.actor}"`)).join('')}</div><div class="section-heading"><h3>${captain?'隊長':this.name(member)}的技能</h3><span>${skills.length} / ${count}</span></div><div class="slot-grid">${Array.from({length:count},(_,i)=>this.button('slot',`<small>技能 ${i+1}</small>${skills[i]?this.title(D.skills[skills[i]]):'<strong>＋</strong><span>選擇技能</span>'}`,`data-kind="skills" data-slot="${i}"`,'loadout-slot '+(skills[i]?'equipped':'empty'))).join('')}</div><p class="page-hint">金幣、餘光、收藏、碎片與永久培養保留；隊長與隊員本局額外成長重置。可沿用目前搭配。</p></div><footer class="outcome-footer">${this.button('retry-start','開始戰鬥','','primary')}</footer></section>`;
  }
  teamPage(){return `<div class="page-tabs">${this.button('team-tab','站位',`data-tab="formation" aria-pressed="${this.team==='formation'}"`)}${this.button('team-tab','配置',`data-tab="config" aria-pressed="${this.team==='config'}"`)}</div>`+(this.team==='formation'?this.formation():this.configuration());}
  formation(){const s=this.session();const cell=(row,slot)=>{const t=s.troops.find(t=>t.row===row&&t.slot===slot),m=t?s.member(t):null;return this.button('position',t?`${U.portrait(t.type)}<strong>${this.name(m)}</strong><span id="page-hp-${t.id}">${this.health(t)}</span>`:`<b>＋</b><span>空位</span>`,`data-row="${row}" data-slot="${slot}" ${t?'data-id="'+t.memberId+'"':''} aria-pressed="${t?.memberId===this.selected}"`,t?'position filled':'position');};
   const selected=s.troops.find(t=>t.memberId===this.selected),bench=s.profile.members.filter(m=>!s.troops.some(t=>t.memberId===m.id));
   return `<div class="formation-head"><span>隊長固定在左側</span><b>${s.troops.length} / 3</b></div><div class="formation-board"><div class="formation-captain">${U.portrait('captain')}<span>隊長</span></div><div class="formation-column"><small>後排</small>${[0,1,2].map(i=>cell('back',i)).join('')}</div><div class="formation-column"><small>前排</small>${[0,1,2].map(i=>cell('front',i)).join('')}</div><div class="enemy-direction">敵<br>人<br>←</div></div><p class="page-hint">${selected?'已選 '+this.name(s.member(selected))+'，再點位置移動／互換，或選擇下方操作。':'點隊員調整位置或配置；點空位加入隊員。最多三人，也能單人出發。'}</p>${selected?`<div class="formation-actions">${this.button('member-config','配置／培養',`data-id="${this.selected}"`)}${this.button('replace-member','更換隊員',`data-id="${this.selected}"`)}${this.button('remove-member','移至待命',`data-id="${this.selected}"`)}</div>`:''}<div class="section-heading"><h3>待命隊員</h3><span>${bench.length} 人</span></div><div class="bench-list">${bench.map(m=>`<article class="bench-card">${this.button('member-config',`${U.portrait(m.type)}<span>${this.name(m)}<small>查看配置與永久培養</small></span>`,`data-id="${m.id}"`,'bench-profile')}${this.button('bench-add',selected?'替換入隊':'加入前排',`data-id="${m.id}" ${!selected&&s.troops.length>=3?'disabled':''}`,'bench-join')}</article>`).join('')||'<p class="page-hint">目前沒有待命隊員，可前往募集招募新夥伴。</p>'}</div>${!bench.length?this.button('nav','前往募集','data-tab="recruit"'):''}${!selected&&s.troops.length>=3&&bench.length?'<p class="page-hint">出戰已滿三人。先點上方隊員，再選待命隊員替換。</p>':''}<details class="page-explain"><summary>受擊與換人規則</summary><p>一般攻擊隨機命中一名存活前排；沒有前排才攻擊後排，所有隊員倒下才打隊長。連擊鎖定同一目標。特殊攻擊依敵人讀條提示。</p><p>更換不回滿 HP、不重置狀態與回場倒數；待命隊員不攻擊。倒下後原位回場。</p></details>`;
  }
  health(t){return t.hp>0?Math.ceil(t.hp)+' / '+Math.round(t.maxHp):'回場 '+Math.ceil(Math.max(0,t.reviveAt-this.session().time))+' 秒';}
  configuration(showActors=true){const s=this.session(),actors=[{id:'player',type:'captain'},...s.troops.map(t=>({id:t.memberId,type:t.type}))];if(this.actor!=='player'&&!s.profile.members.some(m=>m.id===this.actor))this.actor='player';const captain=this.actor==='player',m=s.profile.members.find(m=>m.id===this.actor),stats=captain?s.maxStats():s.memberStats(m),slots=captain?{moves:4,skills:4}:s.slots(m),moves=captain?s.build.moves:m.moves,skills=captain?s.build.talents:m.skills;
   const strip=showActors?`<div class="actor-strip">${actors.map(a=>this.button('actor',`${U.portrait(a.type)}<span>${a.id==='player'?'隊長':S.config.troops[a.type].name}</span>`,`data-id="${a.id}" aria-pressed="${a.id===this.actor}"`)).join('')}${!captain&&!actors.some(a=>a.id===this.actor)?this.button('actor',`${U.portrait(m.type)}<span>待命 · ${this.name(m)}</span>`,`data-id="${m.id}" aria-pressed="true"`):''}</div>`:'';
   const tabs=captain?'':`<div class="page-tabs member-tabs">${this.button('member-view','配置',`data-view="config" aria-pressed="${this.memberView==='config'}"`)}${this.button('member-view','永久培養',`data-view="cultivate" aria-pressed="${this.memberView==='cultivate'}"`)}</div>`;
   if(!captain&&this.memberView==='cultivate')return strip+tabs+this.cultivationPage(m);
   const slot=(kind,i,id,label)=>this.button('slot',`<small>${label}</small>${id?this.title(D[kind][id]):'<strong>＋</strong><span>選擇'+(kind==='moves'?'招式':'技能')+'</span>'}`,`data-kind="${kind}" data-slot="${i}"`, 'loadout-slot '+(id?'equipped':'empty'));
   return strip+tabs+`<article class="actor-summary">${U.portrait(captain?'captain':m.type)}<div><h3>${captain?'遠征隊長 · '+s.grade():this.name(m)}</h3><p>HP ${Math.round(stats.hp)}${captain?' · SP '+Math.round(stats.stamina)+' · MP '+Math.round(stats.mana):' · 攻擊 '+stats.attack}</p><small>${captain?'由你施放招式':'自動輪流出招 · 不消耗 MP／SP'}</small><details><summary>能力與特性</summary><p>${captain?'攻擊力 '+stats.attack.toFixed(1)+' · 魔法攻擊力 '+stats.magicAttack.toFixed(1)+'<br>速度 '+stats.agility.toFixed(1)+' · 運氣 '+stats.luck.toFixed(1):esc(S.config.troops[m.type].description)+'<br>速度 '+stats.speed.toFixed(1)+' · 運氣 '+stats.luck.toFixed(1)+'<br>基礎出手間隔 '+stats.interval.toFixed(2)+' 秒<br>'+slots.moves+' 招式欄 · '+slots.skills+' 技能欄'}</p></details></div></article><div class="section-heading"><h3>${captain?'招式與必殺':'自動招式'}</h3><span>可隨時更換</span></div>${captain?`<div class="config-diamond">${moves.map((id,i)=>`<div class="config-dir-${i}">${slot('moves',i,id,'招式 '+'ABCD'[i])}</div>`).join('')}<div class="config-ultimate">${slot('moves',4,s.build.ultimate,'必殺')}</div></div>`:`<div class="slot-grid">${Array.from({length:slots.moves},(_,i)=>slot('moves',i,moves[i],'招式 '+(i+1))).join('')}</div><p class="page-hint">${(S.config.troops[m.type].archetype||m.type)==='striker'?'可裝備物理招式':(S.config.troops[m.type].archetype||m.type)==='guard'?'可裝備物理招式與前／後排護盾':'可裝備魔法與治療輔助招式'}。未裝備任何招式時使用兵種普攻；已裝備招式依攻擊力計算傷害、依速度讀條。</p>`}<div class="section-heading"><h3>被動技能</h3><span>${this.canSkills()?'出發前配置':'本次遠征已鎖定'}</span></div><div class="slot-grid">${Array.from({length:slots.skills},(_,i)=>slot('skills',i,skills[i],'技能 '+(i+1))).join('')}</div><p class="page-hint">技能僅能在出發前或結算後更換。暫停不會解除配置鎖定。</p>`;
  }
  cultivationPage(m){const s=this.session(),M=S.Members,c=M.cultivation(m),current=clone(m);M.reset(current);const before=s.memberStats(current),slots=s.slots(current),next=clone(current);if(c.next)M.cultivate(next);const after=s.memberStats(next),nextSlots=s.slots(next),held=s.profile.fragments[c.fragmentGrade],ready=this.canSkills()&&!!c.next&&held>=c.cost;
   return `<section class="cultivation-page"><article class="cultivation-hero">${U.portrait(m.type)}<div><small>永久培養 · ${esc(S.config.troops[m.type].name)}</small><h3>${c.grade}${c.next?'<span> → </span>'+c.next:''}</h3><p>目前本局階級 ${M.grade(m)}<br>下一局從永久階級 ${c.grade} 開始</p></div></article><div class="cultivation-path" aria-label="永久培養進度">${Array.from({length:c.max+1},(_,i)=>`<span ${i===c.step?'aria-current="step"':''}>${M.permanentGrade({...current,permanentStep:i})}</span>`).join('')}</div><div class="section-heading"><h3>${c.next?'提升後的起始能力':'起始能力'}</h3><span>本局額外成長不列入</span></div><div class="cultivation-stats">${[['hp','HP'],['attack','攻擊力'],['speed','速度'],['luck','運氣']].map(([key,label])=>`<div><span>${label}</span><strong>${Number(before[key].toFixed(1))}${c.next?` <i>→</i> ${Number(after[key].toFixed(1))}`:''}</strong>${c.next?`<small>+${Number((after[key]-before[key]).toFixed(1))}</small>`:''}</div>`).join('')}<div><span>招式欄</span><strong>${slots.moves}${c.next?' → '+nextSlots.moves:''}</strong></div><div><span>技能欄</span><strong>${slots.skills}${c.next?' → '+nextSlots.skills:''}</strong></div></div><article class="cultivation-materials"><h3>所需素材</h3>${c.next?`<div><span>${c.fragmentGrade} 級共用碎片</span><strong>${held} <small>/ ${c.cost}</small></strong></div><p>${held<c.cost?'還需 '+(c.cost-held)+' 個碎片；招募重複隊員可取得。':'素材已備齊。'}</p>`:'<p>已達永久培養上限。</p>'}</article>${!this.canSkills()?'<p class="config-lock">出發前或結算後才能永久培養。</p>':''}${c.next?this.button('member-cultivate','培養至 '+c.next,`data-id="${m.id}" ${ready?'':'disabled'}`,'primary cultivation-confirm'):''}<p class="page-hint">永久階級與欄位保留到下局；本局額外成長會重置。配置分頁可查看與調整招式。</p></section>`;
  }
  collectionPage(){const s=this.session(),p=s.profile;return `<div class="wallet-compact"><span>${U.icon('coin')}${p.gold.toLocaleString()}</span><span>${U.icon('star')}${p.afterlight.toLocaleString()}</span></div><div class="page-tabs">${[['moves','招式'],['skills','技能'],['members','隊員']].map(([id,label])=>this.button('collection-tab',label,`data-tab="${id}" aria-pressed="${this.collection===id}"`)).join('')}</div>`+(this.collection==='members'?this.memberCollection():this.itemList(this.collection,false));}
  memberCollection(){const s=this.session();return `<p class="page-hint">隊員永久收藏；碎片培養永久保留，本局額外成長會重置。相同兵種與原始稀有度重複招募時轉為碎片。</p><div class="collection-grid">${Object.keys(S.config.troops).map(type=>{const owned=s.profile.members.filter(m=>m.type===type);return this.button('member-detail',`${U.portrait(type)}<strong>${esc(S.config.troops[type].name)}</strong><small>${owned.length?'已收藏 '+owned.length+' 人':'尚未招募'}</small>`,`data-type="${type}"`,'collection-card');}).join('')}</div>`;}
  memberList(records){const s=this.session();return records.map(m=>{const p=S.Members.progress(m),c=S.Members.cultivation(m),d=s.memberStats(m),active=s.troops.find(t=>t.memberId===m.id);return `<article class="member-record"><div class="member-card-top">${U.portrait(m.type)}<header><strong>${this.name(m)}</strong><span>${active?(active.row==='front'?'前排':'後排')+' · 出戰中':'待命'} · #${m.id.slice(7)}</span></header></div><p>HP <b>${d.hp}</b> · 攻擊 <b>${d.attack}</b> · 速度 ${d.speed.toFixed(1)} · 運氣 ${d.luck.toFixed(1)}</p><div class="training-rail"><i style="width:${p.ratio*100}%"></i></div><small>${p.next?'本局成長至 '+p.next+' · '+p.current+' / '+p.required:'本局成長已達上限'}</small><p class="permanent-note">永久起始階級 ${c.grade}</p><div class="member-card-actions">${this.button('member-config','配置招式與技能',`data-id="${m.id}"`)}${this.button('member-config','永久培養',`data-id="${m.id}" data-view="cultivate"`)}</div></article>`;}).join('');}
  recruitPage(){const s=this.session(),r=S.config.collectionRules,w=r.rarityWeights,kind=this.study,pool=kind==='moves'?S.config.moves:S.config.loop.rewards.skillPool,available=pool.filter(id=>!(s.profile[kind][id]>0)&&(D[kind][id].powerGrade||'C')===this.shopGrade),item=this.exchangeId?D[kind][this.exchangeId]:null;
   const result=this.shopResult?`<article class="selection-preview" role="status"><small>${this.shopResult.duplicate?'重複收藏':'新收藏'}</small><h3>${esc(this.shopResult.name)}</h3><p>${esc(this.shopResult.text)}</p></article>`:'';
   return `<div class="wallet-compact"><span>金幣 ${s.profile.gold}</span><span>餘光 ${s.profile.afterlight}</span><span>研習 ${s.profile.researchPoints}</span></div><div class="page-tabs">${[['recruit','招募'],['research','研習']].map(([id,label])=>this.button('shop-tab',label,`data-tab="${id}" aria-pressed="${this.shop===id}"`)).join('')}</div>${result}<div class="fragment-wallet" aria-label="共用隊員碎片">${Object.entries(s.profile.fragments).map(([grade,n])=>`<span>${grade} 碎片 <b>${n}</b></span>`).join('')}</div>`+(this.shop==='recruit'?`<section class="recruit-banner"><h3>旅途中的夥伴</h3><p>${Object.values(S.config.troops).map(t=>t.name).join('／')}，各 1/${Object.keys(S.config.troops).length}。隊員永久保留，每局從永久培養階級開始，最高到當前大階的 ＋。相同兵種與原始稀有度的重複招募會轉為 5 個該級共用碎片；不同稀有度另存一名隊員。</p>${this.button('recruit-draw',`招募一名 · ${r.recruitCost} 金幣`,s.profile.gold<r.recruitCost?'disabled':'','primary')}</section><p class="page-hint">稀有度機率：${Object.entries(w).map(([g,n])=>g+' '+n+'%').join(' · ')}</p><h3>已加入的隊員 · ${s.profile.members.length} 人</h3>${this.memberList(s.profile.members)}`:`<div class="page-tabs">${[['moves','招式'],['skills','技能']].map(([id,label])=>this.button('study-tab',label,`data-kind="${id}" aria-pressed="${kind===id}"`)).join('')}</div><section class="recruit-banner"><h3>${kind==='moves'?'招式':'技能'}研習</h3><p>新內容永久收藏；重複轉為研習點數。招式可隨時裝備，技能於出發前或結算後配置。</p>${this.button('research-draw',`研習一次 · ${r.researchCost} 餘光`,s.profile.afterlight<r.researchCost?'disabled':'','primary')}</section><p class="page-hint">稀有度：${Object.entries(w).map(([g,n])=>g+' '+n+'%').join(' · ')}。各階內等機率；缺少某階時，按現有階權重重新分配。<br>重複所得點數：${Object.entries(r.duplicatePoints).map(([g,n])=>g+' '+n).join(' · ')}</p><h3>指定收藏兌換</h3><div class="page-tabs">${Object.keys(w).map(g=>this.button('exchange-grade',g,`data-grade="${g}" aria-pressed="${g===this.shopGrade}"`)).join('')}</div><p class="page-hint">${this.shopGrade} 級兌換：${r.exchangeCosts[this.shopGrade]} 研習點數 · 僅顯示未收藏內容。</p>${item?`<article class="selection-preview">${this.title(item)}<p>${esc(this.description(item))}</p>${this.button('exchange-confirm',`確認兌換 · ${r.exchangeCosts[item.powerGrade||'C']} 點`,`data-id="${item.id}" ${s.profile.researchPoints<r.exchangeCosts[item.powerGrade||'C']?'disabled':''}`,'primary')}</article>`:''}<div class="collection-grid">${available.map(id=>this.button('exchange-preview',this.title(D[kind][id]),`data-id="${id}"`,'collection-card')).join('')||'<p>此階內容已全數收藏。</p>'}</div>`);
  }
  settingsPage(){return `<div class="settings-card"><div><strong>減少動態演出</strong><p>不影響戰鬥速度。</p></div>${this.button('motion',this.api.reduced()?'開啟':'關閉',`aria-pressed="${this.api.reduced()}"`,'setting-toggle')}</div><div class="settings-card"><div><strong>直式全螢幕</strong><p>支援時鎖定直式。</p></div>${this.button('fullscreen','開啟')}</div><div class="settings-card"><div><strong>自動施放必殺</strong><p>普通招式仍由你操作。</p></div>${this.button('auto',this.session().autoUltimate?'開啟':'關閉',`aria-pressed="${this.session().autoUltimate}"`,'setting-toggle')}</div><div class="settings-card"><div><strong>自動施放招式 A</strong><p>自動使用第一個招式，仍消耗固定 MP／SP；必殺優先。</p></div>${this.button('auto-first',this.session().autoFirst?'開啟':'關閉',`aria-pressed="${this.session().autoFirst}"`,'setting-toggle')}</div><div class="settings-card"><div><strong>離線冒險已啟用</strong><p>關閉或切到背景後，下次回來補算戰鬥與收穫。隊長倒下即停止，手動暫停不會推進。</p></div></div><div class="connection-card">${U.icon('check')}<div><strong>進度自動儲存</strong><p>${esc(root.GameOffline?.status||'以 HTTPS 開啟，可下載完整離線資源。')}</p></div></div><small class="version-note">AFTERLIGHT · v${D.release.version}<br>${D.release.date}</small><p class="page-hint">切換分頁不會暫停；使用上方暫停按鈕才會停止戰鬥。</p>`;}
  itemList(kind,picking){const s=this.session(),owned=s.profile[kind],catalog=kind==='moves'?S.config.moves:S.config.loop.rewards.skillPool,member=this.actor==='player'?null:s.profile.members.find(m=>m.id===this.actor),ids=catalog.filter(id=>D[kind][id]&&(!picking||kind!=='moves'||(!member&&this.picker?.slot===4)||D.moves[id].kind==='normal'));let list=ids.filter(id=>owned[id]>0);
   const compatible=id=>!picking||!member||s.compatible(member,id,kind);if(picking&&!this.showIncompatible)list=list.filter(compatible);if(this.filter!=='all')list=list.filter(id=>kind==='moves'?D.moves[id].damageType===this.filter:D.skills[id].category===this.filter);const grades={C:0,B:1,A:2,S:3,SS:4};list.sort((a,b)=>this.sort==='name'?D[kind][a].name.localeCompare(D[kind][b].name,'zh-Hant'):this.sort==='type'?String(D[kind][a].damageType||D[kind][a].category).localeCompare(String(D[kind][b].damageType||D[kind][b].category)): (grades[D[kind][b].powerGrade||'C']-grades[D[kind][a].powerGrade||'C'])||D[kind][a].name.localeCompare(D[kind][b].name,'zh-Hant'));
   const categories=kind==='moves'?[['physical','物理'],['magic','魔法']]:[...new Set(ids.map(id=>D.skills[id].category||'legacy'))].map(c=>[c,{legacy:'能力',basic:'強化',growth:'本局成長',physical:'物理',magic:'魔法',survival:'生存',weapon:'武器',special:'特殊',resource:'資源',metal:'金屬性',wood:'木屬性',water:'水屬性',fire:'火屬性',earth:'土屬性',light:'光屬性',dark:'闇屬性',luck:'運氣',ultimate:'必殺',hybrid:'通用',cross_element:'元素搭配',control:'控制',defense:'防護',healing:'治療'}[c]||c]);
   return `<div class="list-toolbar"><span>${Object.keys(owned).filter(id=>ids.includes(id)&&owned[id]>0).length} / ${ids.length}</span><select id="page-filter" aria-label="類型"><option value="all" ${this.filter==='all'?'selected':''}>所有類型</option>${categories.map(([id,name])=>`<option value="${id}" ${this.filter===id?'selected':''}>${name}</option>`).join('')}</select><select id="page-sort" aria-label="排列方式">${[['grade','稀有度'],['type','類型'],['name','名稱']].map(([id,name])=>`<option value="${id}" ${this.sort===id?'selected':''}>${name}</option>`).join('')}</select></div>${picking&&member?this.button('incompatible',this.showIncompatible?'隱藏不相容':'顯示不相容'):''}<div class="collection-grid">${list.map(id=>{const item=D[kind][id],known=owned[id]>0,ok=compatible(id);return this.button(picking?'preview':'item-detail',`${U.icon(known?item.icon:'lock')}<em class="item-grade">${known?item.powerGrade||'C':'?'}</em>${known?this.title(item):'<strong>未知'+(kind==='moves'?'招式':'技能')+'</strong>'}<small>${!known?'尚未收藏':!ok?'此隊員不相容':kind==='moves'?(picking&&member?'隊員無消耗':U.cost(item)):'永久收藏 ×'+owned[id]}</small>`,`data-id="${id}" data-kind="${kind}" ${picking?'aria-pressed="'+(this.preview===id)+'"':''} ${!known?'disabled':''}`, 'collection-card '+(!ok?'incompatible':''));}).join('')||'<p class="page-hint">沒有符合條件的收藏。</p>'}</div>`;
  }
  chooser(){const s=this.session(),p=this.picker;if(p.kind==='members')return `<section class="picker-view"><header class="picker-heading">${this.button('picker-back','← 返回站位')}<div><small>${p.row==='front'?'前排':'後排'} · 位置 ${p.slot+1}</small><h2>選擇入隊成員</h2></div></header><div class="picker-scroll">${s.profile.members.map(m=>this.button('choose-member',`${U.portrait(m.type)}<span>${this.name(m)}<small>${s.troops.some(t=>t.memberId===m.id)?'出戰中 · 互換位置':'待命'}</small></span>`,`data-id="${m.id}"`,'member-choice')).join('')}</div></section>`;
   const item=this.preview?D[p.kind][this.preview]:null,m=this.actor==='player'?null:s.profile.members.find(m=>m.id===this.actor),compatible=!m||!item||s.compatible(m,item.id,p.kind),locked=p.kind==='skills'&&!this.canSkills(),clearable=p.kind==='skills'||!!m;
   return `<section class="picker-view"><header class="picker-heading">${this.button('picker-back','← 返回')}<div><small>${m?esc(S.config.troops[m.type].name):'隊長'} · ${p.kind==='moves'?(p.slot===4?'必殺':'招式 '+(m?p.slot+1:'ABCD'[p.slot])):'技能 '+(p.slot+1)}</small><h2>${p.kind==='moves'?'選擇招式':'選擇技能'}</h2></div></header><div class="picker-scroll">${locked?'<p class="config-lock">本次技能已鎖定；可查看，結算後才能更換。</p>':''}${item?`<article class="selection-preview" aria-live="polite">${this.title(item)}<p>${esc(this.description(item,!!m))}</p>${p.kind==='moves'?`<p>${esc(U.effects(item))}</p><small>${m?'隊員無消耗 · 讀條 '+this.memberCast(m,item).toFixed(2)+' 秒':U.cost(item)}</small>`:''}${!compatible?'<p class="config-lock">此兵種無法裝備這項內容。</p>':''}</article>`:'<p class="page-hint">先點選收藏查看效果，再按下方確認裝備。</p>'}${this.itemList(p.kind,true)}</div><footer class="picker-footer">${clearable?this.button('unequip','清空此欄',locked?'disabled':''):''}${this.button('equip',item?'確認裝備':'請先選擇',`data-id="${this.preview||''}" ${!item||locked||!compatible?'disabled':''}`,'primary')}</footer></section>`;
  }
  memberCast(m,move){const s=this.session(),t=s.crew.find(t=>t.memberId===m.id);if(s.phase==='fighting'&&s.battle)return s.battle.castDuration(s.battle.getMove(move.id,t),t);const sources=m.skills.map(id=>S.Skills.source(D.skills[id])),stats=s.memberStats(m),fake={id:t.id,hp:t.hp,stats:{hp:stats.hp,agility:stats.speed,luck:stats.luck,mana:0,stamina:0},statuses:{}};const runtime=new root.SkillRuntime.Runtime({time:0,player:null,enemy:null},fake,sources),value=runtime.modify('attackTime',move.attackTime,{move});return Math.max(.5,value/Math.max(1,stats.speed));}
  details(){const d=this.detail;if(d.memberId){this.actor=d.memberId;return this.button('member-back','← 返回')+this.configuration(false);}if(d.type)return this.button('detail-back','← 返回收藏')+`<h3>${esc(S.config.troops[d.type].name)}</h3>`+this.memberList(this.session().profile.members.filter(m=>m.type===d.type));const item=D[d.kind][d.id];return this.button('detail-back','← 返回收藏')+`<article class="selection-preview">${this.title(item)}<p>${esc(this.description(item))}</p>${d.kind==='moves'?`<p>${esc(U.effects(item))}</p><small>${U.cost(item)}</small>`:''}</article><h3>裝備給</h3>${this.button('detail-equip','隊長配置',`data-id="player" data-kind="${d.kind}"`)}${this.session().troops.map(t=>this.button('detail-equip',this.name(this.session().member(t)),`data-id="${t.memberId}" data-kind="${d.kind}" ${!this.session().compatible(this.session().member(t),d.id,d.kind)?'disabled':''}`)).join('')}${d.kind==='skills'&&!this.canSkills()?'<p class="config-lock">遠征中的技能無法更換。</p>':''}`;}
  action(d){if(this.api.busy?.())return;const s=this.session();try{
   if(d.squadAction==='retry-prepare'){if(s.phase!=='defeat')return;this.tab='adventure';this.adventureState='retry';this.actor='player';this.picker=null;this.detail=null;this.node.scrollTop=0;}
   else if(d.squadAction==='retry-start'){if(s.phase!=='defeat'||this.adventureState!=='retry'||this.picker)return;this.api.depart();this.hide();return;}
   else if(d.squadAction==='nav'){this.open(d.tab);return;}
   if(d.squadAction==='shop-tab'){this.shop=d.tab;this.shopResult=null;this.exchangeId=null;}
   else if(d.squadAction==='study-tab'){this.study=d.kind;this.shopResult=null;this.exchangeId=null;}
   else if(d.squadAction==='exchange-grade'){this.shopGrade=d.grade;this.exchangeId=null;}
   else if(d.squadAction==='exchange-preview'){this.exchangeId=d.id;}
   else if(d.squadAction==='recruit-draw'){const m=s.recruit();this.shopResult={duplicate:!!m.duplicate,name:S.config.troops[m.type].name+' '+(m.duplicate?m.rarity:S.Members.grade(m)),text:m.duplicate?'相同兵種與稀有度已收藏，獲得 '+m.fragmentGrade+' 級共用碎片 +'+m.fragments+'。':'已加入永久名冊，可至隊伍頁安排站位。'};this.api.save();}
   else if(d.squadAction==='research-draw'||d.squadAction==='exchange-confirm'){const result=d.squadAction==='research-draw'?s.research(this.study):s.exchange(this.study,d.id);this.shopResult={...result,name:D[this.study][result.id].name,text:result.duplicate?'已收藏，獲得 '+result.points+' 研習點數。':'已永久收藏，可在配置頁查看。'};this.exchangeId=null;this.api.save();}
   else if(d.squadAction==='team-tab'){this.team=d.tab;this.selected=null;}
   else if(d.squadAction==='collection-tab'){this.collection=d.tab;this.filter='all';}
   else if(d.squadAction==='actor'){this.actor=d.id;this.memberView='config';}
   else if(d.squadAction==='position'){if(this.selected){s.placeMember(this.selected,d.row,Number(d.slot));this.selected=null;this.api.save();}else if(d.id)this.selected=d.id;else this.picker={kind:'members',row:d.row,slot:Number(d.slot)};}
   else if(d.squadAction==='remove-member'){s.removeMember(d.id);this.selected=null;this.api.save();}
   else if(d.squadAction==='bench'){this.collection='members';this.tab='collection';}
   else if(d.squadAction==='choose-member'){s.placeMember(d.id,this.picker.row,this.picker.slot);this.picker=null;this.api.save();}
   else if(d.squadAction==='member-cultivate'){const r=s.cultivateMember(d.id);this.api.save();this.api.labels();this.api.message('永久培養突破 · '+r.grade+' → '+r.after);}
   else if(d.squadAction==='member-config'){this.memberReturn={tab:this.tab,team:this.team,detail:clone(this.detail),selected:this.selected};this.tab='team';this.actor=d.id;this.memberView=d.view||'config';this.detail={memberId:d.id};this.node.scrollTop=0;}
   else if(d.squadAction==='member-view'){this.memberView=d.view;this.node.scrollTop=0;}
   else if(d.squadAction==='member-back'){const previous=this.memberReturn||{tab:'team',team:'formation',detail:null,selected:null};Object.assign(this,previous);this.memberReturn=null;this.node.scrollTop=0;}
   else if(d.squadAction==='replace-member'){const t=s.troops.find(t=>t.memberId===d.id);if(t)this.picker={kind:'members',row:t.row,slot:t.slot};}
   else if(d.squadAction==='bench-add'){const t=s.troops.find(t=>t.memberId===this.selected);if(!t&&s.troops.length>=3)throw Error('先選擇一名出戰隊員，再進行替換');const slot=t?t.slot:[0,1,2].find(i=>!s.troops.some(t=>t.row==='front'&&t.slot===i));s.placeMember(d.id,t?t.row:'front',slot);this.selected=null;this.api.save();}
   else if(d.squadAction==='slot'){this.picker={kind:d.kind,slot:Number(d.slot)};this.preview=this.pendingItem?.kind===d.kind?this.pendingItem.id:null;this.pendingItem=null;this.filter='all';}
   else if(d.squadAction==='picker-back'){this.picker=null;this.preview=null;}
   else if(d.squadAction==='preview'){this.preview=d.id;}
   else if(d.squadAction==='incompatible'){this.showIncompatible=!this.showIncompatible;}
   else if(d.squadAction==='equip'||d.squadAction==='unequip'){if(d.squadAction==='equip'&&(!this.preview||d.id!==this.preview))return;this.equip(d.squadAction==='equip'?d.id:null);this.picker=null;this.api.save();this.api.labels();}
   else if(d.squadAction==='item-detail'){this.detail={kind:d.kind,id:d.id};}
   else if(d.squadAction==='member-detail'){this.detail={type:d.type};}
   else if(d.squadAction==='detail-back')this.detail=null;
   else if(d.squadAction==='detail-equip'){this.pendingItem={...this.detail};this.actor=d.id;this.tab='team';this.team='config';this.detail=null;}
   else if(d.squadAction==='depart'){this.api.depart();this.hide();return;}
   else if(d.squadAction==='unpause'){s.paused=false;this.api.save();}
   else if(d.squadAction==='motion')this.api.motion();
   else if(d.squadAction==='fullscreen')this.api.fullscreen();
   else if(d.squadAction==='auto-first'){s.autoFirst=!s.autoFirst;this.api.save();}
   else if(d.squadAction==='auto'){s.autoUltimate=!s.autoUltimate;this.api.save();}
   this.render();
  }catch(e){this.api.message(e.message);}}
  equip(id){const s=this.session(),p=this.picker,member=this.actor==='player'?null:s.profile.members.find(m=>m.id===this.actor);if(member){const moves=clone(member.moves),skills=clone(member.skills),list=p.kind==='moves'?moves:skills;if(id)list[p.slot]=id;else list.splice(p.slot,1);s.setMemberLoadout(member.id,moves.filter(Boolean),skills.filter(Boolean));}else if(p.kind==='skills'){const ids=clone(s.build.talents);if(id)ids[p.slot]=id;else ids.splice(p.slot,1);s.setSkills(ids.filter(Boolean));}else{if(!id)throw Error('隊長需保留四招與必殺');const build=clone(s.build);if(p.slot===4)build.ultimate=id;else build.moves[p.slot]=id;s.setLoadout(build);}}
  refreshCollection(){if(!this.picker&&!this.detail&&['collection','recruit'].includes(this.tab))this.render();}
  tick(){const s=this.session();if(!s)return;if(document.getElementById('squad-game').dataset.screen==='page'){const c=s.phase==='fighting'?s.battle.player:s.captain,hp=Math.max(0,c.hp),max=s.maxStats().hp;document.getElementById('page-battle-stage').textContent=s.started===false?'準備出發':s.phase==='defeat'?'冒險已結束':(s.paused?'已暫停 · ':'')+'第 '+(s.wave+1)+' 場'+(s.encounter().boss?' · BOSS':'');document.getElementById('page-battle-health').textContent=Math.ceil(hp)+' / '+Math.round(max);document.getElementById('page-battle-hp').style.width=Math.min(100,100*hp/max)+'%';const notice=document.getElementById('squad-page-notice');notice.textContent=document.getElementById('squad-message').textContent;notice.hidden=!notice.textContent;}if(this.tab==='team'&&this.team==='formation'&&!this.picker&&!this.detail)for(const t of s.troops){const node=document.getElementById('page-hp-'+t.id);if(node)node.textContent=this.health(t);}}

 }
 root.SquadPages={Pages};
})(globalThis);
